spec-first/connexion

connexion/operation.py
Allow local development without OAuth2 provider. This is also how the Clojure "friboo" library behaves.
=> allow running without OAuth2 token info URL (for local development)

connexion/__init__.py, connexion/api.py, connexion/app.py, connexion/decorators/security.py, connexion/decorators/validation.py, connexion/operation.py, docs/quickstart.rst
This PR modifies the App and API classes to allow the caller to specify a different directory for the swagger-ui files and/or a different URL path to access the API documentation.
Additionally, it does not emit a loud warning if the API spec specifies a security method other than oauth2. Instead, it warns the user (via a lower logging level) that she should handle the security herself (eg, through a custom decorator).
=> Allow configurable path and URL for swagger-ui

connexion/decorators/validation.py, tests/test_validation.py
This PR adds support for validating arrays that are present within the 'query' or 'path' inputs. Prior to this, arrays were only validated if they were present in the 'body' of a request.
A corresponding unit test was also added.
=> Add validation for array types in query or path

connexion/decorators/produces.py
When serializing responses to JSON, don't append 'Z' to datetime objects if they already have an associated timezone; otherwise, datetime strings can violate RFC 3339 (eg: '2015-09-25T23:14:42+00:00Z'). Note the extraneous 'Z' in the example.
=> Serialization: Don't append 'Z' to datetime objects if they already have a timezone

connexion/decorators/parameter.py, connexion/decorators/validation.py, connexion/operation.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py, tests/test_operation.py
=> Handle non object body parameters

connexion/app.py
The Flask app provides a `kwargs` argument called `options` to forwarded them to the underlying **Werkzeug** server. Currently **connexion** does not provide a way to forward parameter to Werkzeug, so I've implemented the parameter passing into the **connexion app**.
We need this to disable the **reloader** in debug mode.
```python
app = connexion.App(
__name__,
port=8000,
specification_dir='/swagger/',
debug=True,
use_reloader=False
)
```
=> Options Parameter for Werkzeug

connexion/api.py, connexion/app.py, connexion/decorators/decorator.py, connexion/decorators/produces.py, connexion/decorators/response.py, connexion/exceptions.py, connexion/operation.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py
Hi guys,
I wonder if somebody might be willing to review this initial code? (Mentioned by me here: https://github.com/zalando/connexion/issues/76) The idea is to validate the headers and response body returned by the developer from the view func against what was declared in the Swagger specification. If the headers and response schema do not match then an error 500 is generated. I personally think this would be a useful part of the development process because Connexion would be checking to ensure that what is returned as a response actually matches what was promised.
A few notes that came up as I did this work:
1. I passed a reference to the Operation object into the Serializer so that I could access what I needed from the spec. I hope that's okay?
2. The test_app.py unit tests and …
=> Validating the developer's returned response against the specification

connexion/decorators/parameter.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py
Hi,
I think I have hit a small issue this morning with query parameters passed as a "csv array". So my GET request would look something like this:
/v1.0/test_array_csv_query_param?items=one,two,three
And I was getting parameter items like this:
[u'o', u'n', u'e', u',', u't', u'w', u'o', u',', u't', u'h', u'r', u'e', u'e']
(A string cast to a list).
Please take a look at my suggested fix for this in this pull request. I have only supported the "csv" and "pipes" collectedFormat attributes from the swagger spec currently (http://swagger.io/specification/#parameterObject). Tabs and spaces don't make much sense to me as query parameters.
Let me know what you think guys. I've added a couple of tests that hopefully show the behaviour.
=> Fixed an issue with query parameters not properly handling arrays

connexion/operation.py, tests/test_operation.py
closes #94 
adds logic for detecting `x-swagger-router-controller` and if set, will join the `operationId` with this value.
=> added logic for detecting x-swagger-router-controller

connexion/__init__.py, connexion/api.py, connexion/app.py, connexion/operation.py, connexion/resolver.py, connexion/utils.py, tests/fakeapi/__init__.py, tests/fakeapi/hello.py, tests/test_api.py, tests/test_app.py, tests/test_operation.py, tests/test_resolver.py
Adds a `default_controller_name` and uses HTTP method name in absence of `operationId`. See #98
=> Sensible defaults for controller resolution

connexion/resolver.py, tests/fakeapi/foo_bar.py, tests/test_resolver.py
Minor improvement which will replace dashes to underscores in the resource name in the URI path.
=> Handle dashes in resource names in RestyResolver

README.rst
Added documentation for endpoint routing customization and the use of x-router-controller.
=> Updated endpoint routing docs

connexion/utils.py, tests/test_app.py, tests/test_utils.py
I think 'True' / 'False' should be allowed for query parameters. And that would also make swagger client like Bravado compatible with connexion (as it send query parameters with a capital letter).
=> Allow True/False for query parameters

connexion/decorators/parameter.py, connexion/decorators/validation.py, connexion/operation.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py, tests/test_operation.py
In this PR I have implemented support for defaults for query and body parameters. Support for header parameters is not implemented because headers and not treated as arguments to functions. If this changes in the future then adding the support is not difficult. Finally there is no support for _default_ in individual fields of object types. I think this is not directly related to the parameters it can be implemented in another PR.
=> Support for default fields in operation parameters

README.rst
Minor documentation fix for issue #128. Documentation incorrectly referred to the operation property `x-router-controller`, which should actually be `x-swagger-router-controller`.
=> Fix #128 - document `x-swagger-router-controller`

connexion/utils.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py, tests/test_utils.py
This PR fixes the issue #127. 
[Here](http://www.yaml.org/spec/1.2/spec.html#id2803629) in the spec, it seems that Booleans can be true or false, without quotes.
=> Handle correctly boolean values in default property

connexion/decorators/parameter.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py
As already commented in https://github.com/zalando/connexion/issues/132 this PR adds support to pass formData parameters as keyword parameters to function handlers.
=> Pass formData parameters as keyword arguments

connexion/decorators/decorator.py, connexion/decorators/produces.py, connexion/utils.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py
Fixes #133 
The function [`redirect`](https://github.com/mitsuhiko/flask/blob/master/flask/__init__.py#L18) does not return a `flask.Response` instance, but a [Werkzeug response](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/wrappers.py#L1838) causing the Connexion code to break.
=> Fix when API returns flask response

connexion/decorators/response.py, connexion/operation.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py, tests/test_operation.py
Connexion doesn't currently support references in many places explicitly supported by the spec.  A reference in a typed map (e.g. the example under Model with Map/Dictionary Properties at http://swagger.io/specification/) would fail.  Also, circular references, like those used in a tree structure, would also fail.  Though spec doesn't specifically claim to support them, this [bug](https://github.com/swagger-api/swagger-codegen/issues/728) seems to suggest that most implementations should.  
The solution attached leaves most of the reference resolution up to jsonschema, and just copies the definitions as necessary to individual schema objects.
=> Added support for circular references and additionalProperties

connexion/decorators/produces.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py
Fixes #144 
Connexion should support header parameters on 204 response codes. As specified in [RFC-2616 section 10.2.5](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) of HTTP/1.1. Also if you define in your OpenAPI yaml like that:
```yaml
/test-204-with-headers:
get:
summary: Tests that response code 204 can have headers set
operationId: fakeapi.hello.test_204_with_headers
responses:
204:
headers:
X-Something:
description: A value that might be send in the response
type: string
description: 204 no content
```
And your handler function (`fakeapi.hello.test_204_with_headers`) do not set the "X-Something" header Connexion will throw an exception (500 Internal Error) that notifying you that the "X-Something" header wasn't set in the response of your handler. But when you set the …
=> Support header params on 204 response code

.gitignore, examples/basicauth/app.py, setup.py, tests/test_parameter.py, tox.ini
The `functools.wraps` does not pass the information about parameters of the original function to the decorated instance. This makes Connexion fail to get the argument list defined in the original function. So in case you create a decorator with `functools.wraps` and use in your Connexion view function with parameters it will fail on **Python 2.x**.
Due to that problem we should advise the users of Connexion to use the [`decorator`](https://github.com/micheles/decorator) package while creating decorators for their Connexion view functions. This will keep Connextion working as expected specially in case of handing endpoints with parameters in decorated view functions.
Updates our `/basicauth` example project to use the `decorator` package so it drives the users to the recommended usage. …
=> Recommend usage of `decorator` package in Connexion projects

connexion/api.py, connexion/decorators/parameter.py, connexion/operation.py, tests/fakeapi/api.yaml, tests/fakeapi/hello.py, tests/test_app.py, tests/test_operation.py, tests/test_resolver.py, tox.ini
OpenAPI Specification allow [parameters definitions in path level](http://swagger.io/specification/#pathItemObject) of the API specification, but connexion did not support that. This PR adds support for that in Connexion.
More clear error message when there is no parameter defined for a endpoint and the function expects an argument. Before user was just seeing a `TypeError` and it was very obscure to identify what was going on underneath.
Related to #48
=> Support parameters definitions in path level

connexion/api.py, connexion/app.py, tests/fakeapi/api.yaml, tests/fakeapi/module_with_error.py, tests/fakeapi/op_error_api.yaml, tests/test_api.py
Fixes #155.
Question is should we change that behaviour in Connexion? It is a breaking change since older versions would keep going even if the `operationId` is invalid.
=> App breaks if error adding operation raise exception

connexion/decorators/security.py, examples/oauth2/app.yaml, tests/decorators/test_security.py
Fixes 148.
- Remove all usages of the HTTP_TOKENINFO_URL environment variable
=> Remove usage of HTTP_TOKENINFO_URL environment variable

connexion/app.py
When using the tornado web server, the following error was thrown: 
TypeError: _log() got an unexpected keyword argument 'port'
This is resolved by removing the assignment in the logging statement in the tornado section of the app run function.
=> Remove assignment to prevent unexpected keyword argument 'port' error

connexion/decorators/response.py, connexion/decorators/validation.py
Code cleaning. This remove an unnecessary argument in `decorators.py:RequestBodyValidator.validate_schema` method.
- Remove the argument `schema` which this value is already available in an instance attribute of `RequestBodyValidator`.
=> Remove unecessary argument

connexion/api.py, connexion/decorators/response.py, connexion/decorators/validation.py, connexion/exceptions.py, tests/api/test_headers.py
Fixes #153 .
- let the validation error be a validation error
- catch the validation error when validating the response
- create exceptions for nonconforming body and headers and use them to differentiate between the different validation errors and to populate a problem response
=> Better error handling for non-conforming responses

connexion/api.py, connexion/operation.py, tests/api/test_schema.py, tests/fakeapi/hello.py, tests/fixtures/different_schemas/swagger.yaml, tests/test_operation.py
Fixes #180 .
As described in [Swagger Specification](http://swagger.io/specification/#responsesDefinitionsObject) it is possible to define global responses to be used in endpoint specs.
- Added possibility to reference (exp.: `$ref: '#/responses/Something'`) responses defined globally in specification.
=> Response definitions can be defined globally in spec

connexion/decorators/parameter.py, connexion/decorators/validation.py, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Fixes #191.
- Pass files (which are of type FileStorage in werkzeug) from the flask request (`flask.request.files`) to the handler function. Previously these were dropped, as flask seems to take these out of the form data (`flask.request.form`).
- This enables file uploads (via multipart/form mimetype) to work, and for the filelike FileStorage object to make it to the handler.
I haven't included any tests, but I've manually tested.
=> Allow files to be passed into handler

connexion/decorators/parameter.py, connexion/decorators/validation.py, connexion/operation.py, connexion/utils.py, docs/request.rst, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Partially solves #182.
Add support to `x-nullable` vendor extension in Connexion. It is a [ongoing discussion](https://github.com/OAI/OpenAPI-Specification/issues/229) in OpenAPI spec, but requested by users of Connexion and acknowledged as a valid use case.
- Add support for attribute `x-nullable` flag in parameter definitions.
- Add documentation for `x-nullable` flag usage.
=> Support nullable parameters

connexion/__init__.py
Fixes #194
Add placeholder and comment to avoid misunderstanding about versions in development mode.
- Change placeholder version to be `2016.0.dev1`
- Add note to inform that versions are generated during release process.
=> Real version is generated during release process

connexion/app.py, connexion/decorators/produces.py, connexion/decorators/response.py, docs/response.rst, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Fixes #196.
Connexion should remain as must compatible as possible with usual Flask applications. This PR adds back the support of developers to customize the [json_encoder](http://flask.pocoo.org/snippets/119/) in Connexion applications exactly as in pure Flask apps.
- Make use the flask [`JSONEncoder`](http://flask.pocoo.org/docs/0.10/api/#flask.json.JSONEncoder) internally in Connexion.
- Relay on [`flask.Flask.json_encoder`](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.json_encoder) for customization of encoding. This makes possible for users of Connexion to override the encoder they wanna use.
- Adds documentation for this feature.
=> Json encoder customization

connexion/decorators/produces.py, connexion/problem.py, tests/api/test_bootstrap.py, tests/api/test_parameters.py, tests/test_validation.py
This change makes JSON generation more consistent and human-friendly:
- Adding a trailing newline is nicer to people using `curl` from the command line, without making the machine case worse.
- Add `indent=2` to errors so they are pretty printed as well.
=> Make JSON printing a bit nicer

connexion/decorators/produces.py, connexion/decorators/response.py, connexion/operation.py, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Fixes #203
Connexion should validate the schema of responses that have content-type as JSON.
- Validate using json-schema only responses of operations that produces JSON.
- Makes it possible for Connexion applications to return binary data in operations.
=> Validate accordingly with content-type defined in spec

requirements.txt
Fixes #195
I ran a series of tests using different minimal versions of each requirement of Connexion and found the minimum we need to run.
- Add minimum versions of each requirement of Connexion that have it working across the supported Python versions/implementations.
=> Add minimum versions of dependencies

connexion/app.py
WSGI standard requires the handler to be callable - so either be a method or implement __call__. Currently, in order to use Connexion apps with a WSGI handler, one would have to directly pass the MyApp.app attribute instead of the MyApp instance of the connexion.App class. 
Such behaviour should be discouraged as it can lead to unwanted modification of the attribute and limits the amount of backwards-compatible changes possible in the future. Also, the current implementation leads to unwanted side-effects on IIS / wfastcgi.py which is used on the Azure platform.
This small change makes the App class WSGI-compliant and reduces the use of directly referencing the app attribute from outside the class, which should be considered unsafe.
=> Add __call__ method for WSGI-compliance

connexion/api.py
Fixes #214 
- Copies the spec and passes the copy to validator instead of passing the original spec used later in the code
=> Copy spec before validation occurs

docs/cookbook.rst, docs/index.rst
I think we could have a cookbook section in our documentation to provide tips and codesnippets of Connexion.
- Created section "Cookbook" in Connexion's documentation
- Add section to show "How to create custom format for types in JSON
=> How to create custom format for JSON types

connexion/api.py, tests/fixtures/invalid_schema/swagger.yaml, tests/test_api.py
Fixes #220
If a developer write an invalid Swagger spec the `compatibility_layer` function was failing to navigate through the invalid spec structure misleading to an error in Connexion instead of exposing the invalid Swagger spec structure. Now we defer the handing of the error to the swagger spec validator.
- Verify if the method definition is a dict before calling `.get` in `compatibility_layer` function.
=> Defer user error handing for swagger spec validator

connexion/decorators/response.py, connexion/decorators/validation.py, tests/api/test_headers.py
See https://www.quantifiedcode.com/app/project/6ca6bc4af4224f4586a74658f551a64f?groups=code_patterns%3A4ACGxFj1
I replaced the old style `%` format with the new (? is 9 years still "new") style format and made the header comparison easier to read and understand, while avoiding needless conversions to `set`.
=> Cleanup decorators

connexion/decorators/validation.py, tests/test_validation.py
I noticed this bug while testing a swagger.yaml that included `minItems` and `maxItems` properties on an `array` parameter.
It is quite obvious and self-explanatory.
=> Fix array conversion during validation

connexion/decorators/validation.py, tests/api/test_unordered_definition.py, tests/conftest.py, tests/fakeapi/hello.py, tests/fixtures/unordered_definition/swagger.yaml
Fixes #219  .
- Parameter validation dictionary is built with a default dict instead of `groupby` from `itertools`.
- Tests to verify that the validation now really works.
=> Fix for when parameter spec is unordered.

connexion/app.py, tests/api/test_errors.py, tests/fakeapi/hello.py, tox.ini
Fixes #239
Replaces #237
Simple change makes Connexion compatible with Flask 0.11
Since the Flask 0.11 the supported error handlers are the ones that have specific exception in [werkzeug](https://github.com/pallets/werkzeug). The HTTP error code 402 is not supported by Werkzeug so we cannot use it in tests.
- Calls properly the `add_error_handler` funcion from Flask App
- Fix tests
=> Support flask 0.11

examples/sqlalchemy/app.py, examples/sqlalchemy/orm.py
Tiny code formatting changes (flake8) in SQLAlchemy example provided by @nmusatti.
Using our flake8 settings (defined in `tox.ini`) with max-line-length=120.
=> fix flake8 formatting of SQLAlchemy example

docs/request.rst
I want to add a link to direct users to the proper part of the spec where is possible to find more information about parameters specially the `collectionFormat` definitions.
- Better docs.
=> Add link to official spec

connexion/utils.py, tests/test_api.py, tests/test_utils.py
=> Raise import errors on endpoint handling

connexion/api.py, tests/test_api.py
=> Open spec file as binary and then handle problems with encoding.

connexion/decorators/validation.py
Fixes #234  .
- For request body validations, instead of sending back the entire API schema, Connexion will only send back the error message (eg: "'value' is a required property"
- For response validations, Connexion will continue to log the entire API schema via the `logger.error` call, as it did before.
=> Don't send back entire API schema to clients after validation failures

README.rst, connexion/api.py, connexion/app.py, connexion/decorators/validation.py, connexion/operation.py, docs/request.rst, tests/api/test_bootstrap.py, tests/api/test_parameters.py, tests/conftest.py
Fixes #223 .
- Add logic to validate that the query and formData parameters passed on the request are valid parameters in the swagger spec
- Add a strict_validation flag to `add_api()` and `Api` to enable this validation.
=> Validate parameter list

README.rst
This change fixes the following error when trying the example:
```
Traceback (most recent call last):
File ".../src/app.py", line 5, in <module>
connexionApp = connexion.App(specification_dir='./swagger/')
TypeError: __init__() missing 1 required positional argument: 'import_name'
```
=> Fix forgotten argument in README

setup.py
Fixes #260 .
* Ignore `patchlevel` (which might be non-numeric)
* Simplify comparison
=> Fix setup.py to work with non-numeric Python patchlevel

connexion/decorators/parameter.py, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml, tests/test_parameter.py
Fixes #270.
* support operation functions with `**kwargs`
=> Support operation functions with **kwargs

connexion/decorators/parameter.py, tests/test_parameter.py
Just some suggestions that I would like to had commented on the PR #271.
=> Small refactor for code clarity

connexion/exceptions.py, tests/api/test_bootstrap.py, tests/conftest.py
- Derive from Exception rather than BaseException (see https://www.python.org/dev/peps/pep-0352/)
- Change the expectation that `InvalidSpecification` is only raised outside debug mode.
Note: the latter change is in line with how exceptions are generally handled in connexion. It'd be easy enough to pass this particular error through anyway.
=> It's bad practice to derive custom exception classes from BaseException.

connexion/utils.py, tests/test_utils.py
Swagger is clear on the fact that operationIds must be unique across a spec. That leads to connexion assuming that there is no reason for the same Python function to be mapped to multiple paths, and using the output of `flaskify_endpoint` for unique flask view names.
Now this is correct as connexion is currently implemented. I'm preparing another PR based on #274 that would no longer make this assumption always true.
- Add the ability to *optionally* add random characters to a flask view name
=> Add ability to add random string to endpoint names

tox.ini
It took me a while to dig down to the fact that my global Python3 interpreter has a different version from the tox one, which leads to all sorts of weird default isort behaviour.
With this extra flag, Travis will tell you precisely which imports isort would like to see changed.
=> Add CLI option to isort to output diff of proposed changes.

connexion/cli.py, tests/test_cli.py
- add a --base-path option to the CLI which overrides (or provides) the basePath from the spec
This allows deploying at different paths without editing the API spec.
=> Add a --base-path option to the CLI

connexion/api.py, tests/fixtures/simple/basepath-slash.yaml, tests/test_api.py
Fixes #290.
Strip trailing slashes from `basePath` to fix URL routing.
=> #290 fix basePath with trailing slash

connexion/cli.py, tests/test_cli.py
Fixes #304.
- receive `--host` or `-H` option which defaults to None
- make use of host parameters introduced in  #298 
- test cases where users specify a host and cases when they don’t
We’re using `-H` instead of `-h` in order not to be confused with help arguments.
Fabric also uses `-H` as host parameter.
=> Receiving --host or -H option via CLI and writing test cases.

.gitignore, connexion/__init__.py, connexion/app.py, connexion/decorators/decorator.py, connexion/decorators/produces.py, connexion/decorators/response.py, connexion/decorators/security.py, connexion/decorators/validation.py, connexion/exceptions.py, connexion/handlers.py, connexion/operation.py, connexion/problem.py, connexion/utils.py
- Remove license from every file
- Rename variable named `type` overriding builtin
- Fixes inconsistent function docstring
- Remove ugly `print` statement
=> General clean up

connexion/api.py, connexion/app.py, connexion/cli.py, tests/api/test_bootstrap.py, tests/conftest.py, tests/decorators/test_security.py, tests/fakeapi/hello.py, tests/test_api.py, tests/test_cli.py, tests/test_metrics.py, tests/test_operation.py, tests/test_parameter.py, tests/test_resolver.py, tests/test_utils.py, tests/test_validation.py, tests/util.py, tox.ini
Fixes the isort checks within tox
The idea is that within `connexion`, `connexion` is a first party, within `examples` it's a third party and within `tests` it's a first party as well. It's probably hard to get it working within an editor.
- separate the isort checks per folder
- apply the proposed changes by isort on the existing code
Cheers,
=> Fix isort checks

.travis.yml, connexion/cli.py, requirements-devel.txt, requirements.txt, setup.py, tox.ini
Fixes minimal version for `six` .
**Changes proposed in this pull request:**
[Requirements Builder](https://pypi.python.org/pypi/requirements-builder) provides a way to run tests against all interesting
versions of the requirements: minimal, latest as well as development
(from git, hg, svn).
It requires to move the requirements into the setup.py and to provide a
minimal version. requirements-devel aims at helping you working
* It detected a conflict with six version which had to be bumped up;
* building PyYAML from Subversion fails so it's commented in the
requirement-devel.txt file.
A cool blog post on how to keep some balance between setup.py and
requirements.txt file:
https://caremad.io/posts/2013/07/setup-vs-requirement/
**PS:** the build fails because of the `isort` test which I …
=> Using Requirements Builder for Tox setup

connexion/decorators/parameter.py, docs/routing.rst, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Parameters that are not valid Python names are not handled gracefully at the moment. E.g. OData query parameters (`$skip`, `$top`, `$filter`) are only passed to the controller if it uses `**kwargs`.
Parameter names should be sanitized by stripping invalid characters.
If the controller does not have `**kwargs` there is no way for the parameters to be passed as arguments.
Create a `swagger.yaml` that declares a parameter with a name that is not a valid argument name in Python, such as `$top`.
Output of the commands:
- `python --version`
Python 2.7.12
- `pip show connexion | grep "^Version\:"`
Version: 2016.0.dev1
- `git describe --always`
1.0.88-234-g10a0c15
=> Parameter names are not sanitized

connexion/api.py, connexion/app.py, tests/api/test_bootstrap.py
Fixes #296 
- Add support for an API-dictionary argument to app.add_api() as an alternative to a file path.
- test case creating app and using add_api() with an API-dictionary
- Currently the param is still called swagger_file, this and other params should probably change I am just not sure what to change it to.
=> Support app.add_api() with API-dictionary as an alternative to file path

connexion/decorators/security.py
The Oauth token should never be logged.
=> Don't log Oauth Token

connexion/decorators/security.py, tests/decorators/test_security.py
- Raises an exception in the oAuth security provider instead of returning a flask response
This allows easier overriding of the oAuth security failures because you add your own error handler to customise the response (if you choose not to use the 'application/json+problem' return type):
```
def render_unauthorized(exception):
return Response(response=json.dumps({'error_description': 'Test String', 'error': 'test_error'}), status=401, mimetype="application/json")
app = connexion.App(__name__, specification_dir='./../swagger/', debug=debug, swagger_ui=False)
app = app.add_error_handler(401, render_unauthorized)
```
The current messages will continue to be returned in a b/c way because the current default exception handlers find the exceptions now being …
=> Allow custom rendering of oAuth issues

connexion/app.py, connexion/decorators/decorator.py, connexion/decorators/metrics.py, connexion/decorators/produces.py, connexion/decorators/response.py, connexion/decorators/validation.py, connexion/handlers.py, connexion/operation.py, connexion/problem.py, tests/api/test_bootstrap.py, tests/api/test_responses.py, tests/conftest.py, tests/decorators/test_security.py, tests/fakeapi/hello.py, tests/fixtures/problem/swagger.yaml, tests/fixtures/secure_api/swagger.yaml, tests/fixtures/secure_endpoint/swagger.yaml, tests/fixtures/simple/swagger.yaml, tests/test_metrics.py, tests/test_operation.py, tests/test_validation.py, tests/util.py
Fixes #356,  related to #285
I finally found time to make this change of how Connexion code internally works. I was very bothered by the `get_full_response` method returning multiple values and we were getting lost a lot to sort out those returned values, reusing positions, etc. This caused the #356 and generated #285. It is an old bug that is fixed by this PR. Also this PR makes it easier to maintain the Connexion codebase as we move forward.
- We rely on `ResponseContainer` as a wrapper to whatever the operation handler function returns.
- The `ResponseContainer` object is responsible to manage the data that the operation handler function provided.
- The `ResponseContainer` object is what all internal Connexion decorators interact with and not with …
=> Refactor code to fix confusion with returned values

connexion/operation.py, connexion/utils.py, docs/routing.rst, tests/test_operation.py, tests/test_utils.py
The Flask variable converter "path" allows url variables to include forward slashes in their values. This PR adds support for that feature if the Swagger specification indicates that a route parameter's format is "path". 
Example:
parameters:
- name: name
in: path
required: true
format: path
type: string
will add a route parameter `<path:name>`.
Excerpt from the Swagger specification:
> the format property is an open string-valued property, and can have any value to support documentation needs. Formats such as "email", "uuid", etc., can be used even though they are not defined by this specification.
=> Support the flask url variable converter "path"

connexion/app.py, connexion/exceptions.py, tests/api/test_errors.py, tests/fakeapi/hello.py, tests/fixtures/problem/swagger.yaml
The `ProblemException` is an internal behaviour of Connexion and shouldn't mix with the Flask responses. Furthermore, the previous implementation of the `ProblemException` introduced in #368 could not be converted directly to problem responses. This PR fixed this.
=> Problem as exceptions should convert properly to problem responses

connexion/decorators/parameter.py, connexion/decorators/validation.py, requirements-devel.txt, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Hi, 
While debugging a vague error message ("None type is not of type object"). I came across some deprecated Flask code, so I changed it.
The reason i got the error message was because I had forgotten to set a content-type header to "application/json" in Postman. I thought it would be useful to improve the error message when this happens. 
Let met know what you think!
- refactoring flask.request.json calls to flask.request.get_json()
- Improving error messages when an http request does contain data but lacks a proper content-type
=> Replacing deprecated flask json calls + Content-Type validation

connexion/decorators/produces.py, tests/api/test_bootstrap.py, tests/api/test_errors.py, tests/api/test_headers.py, tests/api/test_parameters.py, tests/api/test_responses.py, tests/api/test_schema.py, tests/api/test_secure_api.py, tests/api/test_unordered_definition.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Issue #395 
Passing keyword argument "encoding=utf-8" to flask.json.dumps to make sure responses are encoded using utf-8.
=> pass encoding=utf-8 keyword argument to flask.json.dumps

release.sh
- Set script flags explicitly for better maintainability;
- Make script portable. This is to be used in MacOS systems (`sed` command interface is slightly different);
- Use `twine` (https://packaging.python.org/distributing/#upload-your-distributions) to securely upload new packages versions to PyPi;
- Signs new release tags.
=> Improve the release script

connexion/api.py, connexion/app.py, connexion/decorators/parameter.py, connexion/operation.py, setup.py, tests/api/test_parameters.py, tests/conftest.py, tests/fakeapi/snake_case.py, tests/fixtures/snake_case/swagger.yaml
Fixes #340 | Convert camelcased parameter names to Python style
- added config variable pythonic_params
- parameter changes made in parameter_to_arg
- sanitize_param made a local function within parameter_to_arg so that it can access pythonic_params as a closure and keep the code a little cleaner
- unit tests added with fakeapi and swagger spec
=> Fixes #340 | Convert camelcased parameter names to Python style

requirements-devel.txt, setup.py, tests/api/test_schema.py, tests/fixtures/different_schemas/swagger.yaml
This pull request removes the unnecessary dependency on strict-rfc3339 specified in setup.py and requirements.txt. Calls to functions of this module were removed in commit 559af21f90e833044be4acdf872ef97d42cb0181 and the actual import in 6554de8dc38a0d04ee4a73b6e4e1a43c2822ab66, both of which were made some time in 2015.
Since strict-rfc3339 is licensed under the GPLv3 and connexion under the Apache 2.0 license, this change also makes it more clear that there is no licensing issue any more.
=> Remove unnecessary dependency on strict-rfc3339

connexion/apis/flask_api.py, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Allows these flask paradigms to work in connexion endpoints:
```python
return jsonify({'foo': 'bar'}), 200
```
```python
return jsonify({'foo': 'bar'), {'new_header': 'header_value'}
```
```python
return jsonify({'foo': 'bar'}), 201, {'new_header': 'header_value'}
```
=> Fix returning flask Response objects in a tuple

connexion/decorators/parameter.py, docs/security.rst, examples/oauth2/app.py, tests/api/test_secure_api.py, tests/fakeapi/hello.py, tests/fixtures/secure_endpoint/swagger.yaml
Fixes #428.
Allow using handler functions without using `user` or `token_info` args (set by security decorator).
=> Ignore context args

connexion/apis/flask_api.py
=> Fix: Do not assign flask response status with an empty http reason

docs/response.rst
After the refactor of uncouple all flask functions from base code, JSONEncoder should be `connexion.apps.flask_app.FlaskJSONEncoder` now.
=> path changes for JSONEncoder

connexion/operation.py
My Swagger spec has multiple security definitions (for Basic auth and JWT/Bearer auth), and whenever I start my server I see lots of output telling me that Connexion isn't going to verify the passed credentials.
This PR downgrades the message severity. There is a similar message at debug level for when the API has Basic auth, as Connexion doesn't validate that either.
```
py27-dredd runtests: commands[1] | ./test_api.sh
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. **IGNORING SECURITY REQUIREMENTS**
[08/May/2017 13:23:17] WARNING connexion.operation ... More than one security requirement defined. …
```
=> Downgrade log message severity when there are multiple security definitions

tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml, tests/test_flask_utils.py
Addresses #449 (adds test) .
None. I wrote a test based on what I expected the behavior to be, prior to making any code changes, and the test passes.  turns out I was using a version of connexion that came with the generated swagger.io stubs, and it is older (connexion-1.0.129), and the path formatting seems to not work as of that version. I upgraded connexion, fixed a small JSON encoding issue with the stub code, and it now runs as expected. But here's a test that covers the scenario I described.
None, just another coverage point.
=> 449 path format

connexion/apps/flask_app.py, tests/api/test_bootstrap.py
Fixes # .
1.1.10 -  introduces one backward incompatible undesired change. it fixes 'server' parameter in FlaskApp initialization making not possible to set server argument with a different value.
- Adding 'server' as a named argument in the flask_app module.
=> solving fixed argument (server) for FlaskApp

setup.py
Fixes #457.
- Don't install typing when using python 3.6
=> Install typing only when needed

.travis.yml, connexion/apis/abstract.py, connexion/decorators/parameter.py, connexion/mock.py, connexion/resolver.py, connexion/utils.py, tests/test_api.py, tests/test_cli.py, tests/test_mock.py, tox.ini
Connexion is mocking all functions even when mocking method is **not** "mock all". This PR fixes that and also remove exposition of Connexion's `ResolverError` internal exception letting go the original exception which will be much more useful for users to debug their applications.
- Fixes mocking partially functions as expected;
- Expose to users native errors when functions are not found. Make much easier to debug problems;
- Log messages when functions are mocked or not. Improve development experience;
- Test under Python 3.6.
=> Fix bug on mocking APIs partially

connexion/decorators/security.py, tests/decorators/test_security.py
Fixes #475. 
I couldn't find a relevant test.
=> Split tokeninfo scope if it is a string

connexion/decorators/response.py, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Currently, if a spec does not define a schema for a response code but defines a default schema, it is not validated.  This change pulls the default schema if the response code lookup fails.
=> Validate responses against the default response field if the code is not found

connexion/mock.py, tests/test_mock.py
Fixes #308 .
Adding support for "example" in definitions to be returned from the mock server instead of "No example response was defined." for more robust mocking.
- If response example is not provided, use "example" defined in response type schema
- If no response example or schema example is provided return error message as before
=> Fix for Issue #308: MockResolver: support "example" in definitions

.travis.yml, requirements-devel.txt, setup.py
Changing package properties dynamically in setup.py means that universal
wheels will actually be built only for the builder's environment, and
might not work properly on different platforms/PYthon versions.
Closes https://github.com/zalando/connexion/issues/493
=> setup.py: Use env markers for Python version-specific dependencies

connexion/decorators/validation.py, tests/api/test_responses.py
At the moment if no `Content-Type` is provided in the request the validation wrapper raises a `KeyError`.
Can we expect a fix to make it into a release soon or should we look for a temporary workaround until that happens?
=> Fix KeyError if no Content-Type was provided in request

connexion/apps/flask_app.py, examples/enforcedefaults/enforcedefaults.py, examples/helloworld/hello.py
Some of the [examples](https://github.com/zalando/connexion/tree/master/examples/) were raising an `Exception` when ran according to the provided `README` documentation. This occurred because the port was passed incorrectly as the `server`-argument. Fixed also the exception string which had incorrect string formatting.
=> Fix the examples

connexion/decorators/parameter.py, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Fixes #485 .
- Use the proper string type based on the python version.
=> Fix UnicodeEncodeError for query-strings on Python 2

tests/test_api.py
Fixes # n/a
- Removes a duplicated test (`fixtures/missing_op_id/swagger.yaml`) in debug mode
As discussed [here](https://github.com/zalando/connexion/pull/454#issuecomment-320214622)
cc @rafaelcaricio
=> Tests; remove duplicate test of missing_op_id in debug mode

connexion/decorators/parameter.py, tests/api/test_parameters.py
Fixes issue #323
This is a better implementation of what I was doing in the #499 pull request.
- On line 146 of parameter.py: updating the request query parameters being added to `query_arguments` so as to preserve lists that are encoded by having multiple values to a single key.
=> Preserving the multiplicity of array type query parameters

CONTRIBUTING.rst, README.rst
Contributors need to be made aware of the terms and conditions under which they contribute to this repository.
=> Add inbound license notice

connexion/apis/flask_api.py, connexion/decorators/response.py, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/swagger.yaml
Python 3.5 introduced a new enumeration "http.HTTPStatus" for
representing HTTP response status codes. The default response validation
introduced in connexion 1.1.12 highlighted the fact that connexion does
not natively support this type and was previously silently ignoring
non-integer status code representations.
This modifies the response validation code to extract the value when
given an enum instead of an int. Somewhat hacky test code is added to
check for enum support on python versions that include
"http.HTTPStatus".
Fixes #503 
- Convert enums to ints in response validation matching.
=> Allow http.HTTPStatus enums as response status codes.

docs/cookbook.rst
Resolved error since flask cors was moved to its own project: `ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.`
Will also require installation `pip install -U flask-cors`
Fixes # .
-
-
-
=> Update CORS documentation

connexion/decorators/parameter.py, requirements-devel.txt, tests/decorators/test_parameter.py
Fixes #469 .
- Pass undocumented path parameters to the handler to allow injection.
=> Restoring Flask-Injector support by passing "undocumented" path parameters to the handler

connexion/apps/flask_app.py, connexion/cli.py, connexion/decorators/security.py, examples/oauth2/mock_tokeninfo.py, examples/oauth2/mock_tokeninfo.yaml, tests/conftest.py
Fixes #541 
- Change token info verification to use Authorization headers rather than url params.
Note: Not sure if url params is a requirement, left it in the test case fixture, but could be removed if Authorization headers would suffice.
=> Use Authorization headers for verifying token info

connexion/apps/flask_app.py, connexion/cli.py
The flake8 checks were failing for py3.5 due to a couple of catch-all
exceptions when importing tornado and gevent libraries. Refactored to
catch the `ImportError`.
=> refactor catch-all exceptions

connexion/decorators/parameter.py, requirements-devel.txt, setup.py, tests/conftest.py, tests/decorators/test_parameter.py, tests/fixtures/query_sanitazion/swagger.yaml
A small bug was introduced in #500 when sanitizing the request query
parameters. Instead of fetching the arguments from `request.query`,
the parameters were sanitized from the `request.form`. This causes an
error log to be printed, as the parameters are not expected for the
query (for example in the case of a POST request).
Fixes #522
=> FIX a typo causing an ERROR log

connexion/decorators/security.py, tests/api/test_secure_api.py, tests/conftest.py
Some oauth libraries use the key 'scopes' instead of 'scope' in the token info response.
https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples
- Allow token info responses that use 'scopes' instead of 'scope'
=> Allow token_info response to use 'scopes' key

connexion/apps/flask_app.py
See https://github.com/gevent/gevent/blob/master/CHANGES.rst#13b2-2018-05-03
```
The long-deprecated and undocumented module gevent.wsgi was removed.
```
- For gevent, replace wsgi references with pywsgi
=> Make compatible with latest gevent version

connexion/apps/abstract.py
- Document that `specification` argument to `AbstractApp.add_api` can be a string
=> Improve docstring for AbstractApp.add_api

.travis.yml, README.rst, connexion/apis/abstract.py, connexion/decorators/parameter.py, connexion/decorators/uri_parsing.py, connexion/decorators/validation.py, connexion/operation.py, connexion/options.py, tests/api/test_bootstrap.py, tests/api/test_parameters.py, tests/decorators/test_uri_parsing.py, tests/fixtures/simple/swagger.yaml, tests/test_validation.py
Fixes #608 
Supersedes #587 
- array logic refactored into one place.
- validation.py and parameter.py no longer try to join the array, and the split it again.
- validation of defaults now works, because the validator is given the correct type.
- some additional classes that change the behavior of deduplicating query parameters that are defined multiple times
- **AlwaysMultiURIParser** that is backwards compatible, warts and all (used by default)
- **Swagger2URIParser** that adheres to the spec's definition of `collectionFormat: multi` and uses the last-defined query parameter value (ex. `query?a=1&a=2` => `a = 2`)
- **FirstValueURIParser** that behaves like Swagger2URIParser, except that the first-defined value is used (ex. `query?a=1&a=2` => `a=1`) …
=> URI parsing decorator

connexion/apis/abstract.py
Created a new method AbstractAPI._validate_spec  to encapsulate the specification validation.
I need this feature because I have a custom validator that I used instead the swagger_spec_validator.
=> create a new method AbstractAPI._validate_spec

tests/fixtures/aiohttp/openapi_empty_base_path.yaml, tests/fixtures/aiohttp/openapi_secure.yaml, tests/fixtures/bad_operations/openapi.yaml, tests/fixtures/bad_specs/openapi.yaml, tests/fixtures/default_param_error/openapi.yaml, tests/fixtures/different_schemas/openapi.yaml, tests/fixtures/missing_implementation/openapi.yaml, tests/fixtures/missing_op_id/openapi.yaml, tests/fixtures/module_does_not_exist/openapi.yaml, tests/fixtures/module_not_implemented/openapi.yaml, tests/fixtures/op_error_api/openapi.yaml, tests/fixtures/problem/openapi.yaml, tests/fixtures/query_sanitazion/openapi.yaml, tests/fixtures/secure_api/openapi.yaml, tests/fixtures/secure_endpoint/openapi.yaml, tests/fixtures/simple/openapi.yaml, tests/fixtures/snake_case/openapi.yaml, tests/fixtures/unordered_definition/openapi.yaml, tests/fixtures/user_module_loading_error/openapi.yaml
first piece of #420 
- add openapi.yaml test fixtures alongside swagger.yaml (converted with [swagger2openapi](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/README.md) , some minor manual edits)
=> Add OpenAPI 3 test fixtures

connexion/decorators/validation.py, tests/api/test_responses.py
Right now request validator returns 415 Unsupported Media Type "Invalid Content-type (application/json), expected JSON data" when Content-Type is set to "application/json" (correctly) but the payload itself is not valid JSON. This error message is misleading into thinking that there is something wrong with Content-Type header (but it's not)
This patch fixes it by separating two cases:
- Request content-type is not JSON, in this case old behaviour is retained
- Request content-type is JSON but payload cannot be parsed into a valid JSON, in this case 400 Bad Request "Request body is not valid JSON" is returned.
=> Correct validator response on bad JSON

README.rst
I think "non-named" word was ill-placed here (at least I did not understand what it meant). I tried to clarify this better and propose a solution to not get a exception.
Slightly changed wording in README
=> Minor change in readme about non-required parameters

connexion/apis/abstract.py, connexion/apis/aiohttp_api.py, connexion/apps/abstract.py, connexion/decorators/parameter.py, connexion/lifecycle.py, connexion/operation.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/decorators/test_parameter.py, tests/fakeapi/aiohttp_handlers.py, tests/fixtures/aiohttp/swagger_simple.yaml
Fixes #603
- Add new argument (currently named `pass_context_arg_name` but could probably use a nicer name) to `connexion.apps.abstract.AbstractApp.add_api` to inject the framework's request context to the handler functions.
=> Add capability to pass framework's request context to handler functions

connexion/operation.py, tests/api/test_bootstrap.py
- removed the validate_defaults method from Operation because the new swagger_spec_validation version do this validation;
- added tests for AbstractApi._handle_add_operation_error.
=> Increase the code coverage

connexion/apis/abstract.py, connexion/decorators/response.py, connexion/jsonref.py, connexion/mock.py, connexion/operation.py, connexion/utils.py, tests/test_operation.py, tests/test_references.py
relates to #624 
This branch factors out reference resolution, and applies it to the spec immediately after it is validated.
Previously this behavior was (1) in operation.py, and (2) tied to the swagger spec implementation.
- make reference resolver general purpose
- resolve references eagerly in `apis/abstract.py` once instead of many times within `operation.py`
Note that the resolve_references function had two main features:
1. resolving references
2. attaching the definitions for use by the validator (this was useful for recursive definitions).
There is now a `with_definitions()` function that attached the definitions to a schema, to be used with the jsonschema validator.
This allows for both eager evaluation, and recursive definitions.
=> resolve json references earlier, generically

connexion/mock.py, tests/test_mock.py
This case is no longer possible since jsonref resolution happens much earlier in api/abstract.py
- remove jsonref resolution code from mock code, tests
=> remove ref resolution from mock code

tests/api/test_bootstrap.py, tests/conftest.py
related to #420 
This includes some of the changes to tests from #639 
I've broken them out because they could be reviewed separately.
- add test parameterization for different spec files (i.e. swagger.yaml, openapi.yaml)
=> parameterize tests

tests/decorators/test_parameter.py
- remove test that relies on log output
=> remove test that relies on log output

README.rst, connexion/apis/abstract.py, connexion/exceptions.py, connexion/operation.py, setup.py, tests/api/test_bootstrap.py, tests/test_api.py, tests/test_operation.py
related to #420 and #639 , this switches to a library that can validate both swagger 2.0 and openapi 3 specs.
- Change validation library from swagger_spec_validator to openapi_spec_validator
=> Switch from swagger_spec_validator to openapi_spec_validator library

docs/routing.rst
Link has markdown syntax in a reStructuredText document.
=> fix link to odata

connexion/apis/abstract.py, connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/options.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/api/test_bootstrap.py
another chunk of #639 
- rename references to the "swagger json" to "openapi json"
- ensure we serve up the spec as it exists on disk ("raw_spec"), not the resolved spec.
Note that the UI component is actually called "swagger-ui".
> ```
> The easiest way to understand the difference is:
> OpenAPI = Specification
> Swagger = Tools for implementing the specification
> ```
More information on naming here: https://swagger.io/blog/api-strategy/difference-between-swagger-and-openapi/
=> update some names from swagger to openapi

MAINTAINERS
Add Daniel Grossmann-Kavanagh as an external contributor to Connexion.
=> Add Daniel Grossmann-Kavanagh as maintainer

connexion/cli.py, tests/test_cli.py
cli.py currently passes old_style_options to the app_cls
=> Fix cli.py app options

connexion/decorators/validation.py
To easily discern response and request validation errors logs
programmatically (e.g. in logging filter).
=> Add validator kind to error logs extra in validators

connexion/decorators/metrics.py
Fixes #665 .
- In case of an HttpException use the status code from the exception to report in the metrics
=> Improve metrics reporting

README.rst, connexion/apis/abstract.py, connexion/decorators/parameter.py, connexion/decorators/uri_parsing.py, connexion/decorators/validation.py, connexion/operations/__init__.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/options.py, setup.py, tests/api/test_bootstrap.py, tests/api/test_parameters.py, tests/conftest.py, tests/decorators/test_uri_parsing.py, tests/fakeapi/hello.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml, tests/test_mock3.py, tests/test_resolver3.py
Fixes #420 
- support openapi version 3
Architecture:
- creates an AbstractOperation class, which defines the interface for what an Operation is
- Implements this interface with Swagger2Operation and OpenAPIOperation classes
- apis/abstract.py uses the correct operation class based on the version of the spec
=> Support OpenAPI 3.0.0 specs

connexion/apis/abstract.py
- don't error if an oas3 spec doesn't contain a servers block
=> missing server block doesn't cause error [oas3]

examples/openapi3/basicauth/README.rst, examples/openapi3/basicauth/app.py, examples/openapi3/basicauth/openapi.yaml, examples/openapi3/helloworld/README.rst, examples/openapi3/helloworld/hello.py, examples/openapi3/helloworld/openapi/helloworld-api.yaml, examples/openapi3/restyresolver/README.rst, examples/openapi3/restyresolver/api/__init__.py, examples/openapi3/restyresolver/api/pets.py, examples/openapi3/restyresolver/resty-api.yaml, examples/openapi3/restyresolver/resty.py, examples/openapi3/sqlalchemy/README.rst, examples/openapi3/sqlalchemy/app.py, examples/openapi3/sqlalchemy/openapi.yaml, examples/openapi3/sqlalchemy/orm.py, examples/openapi3/sqlalchemy/requirements.txt
Relates to #420 
Split out examples from #621 to make code review easier.
- move existing examples under examples/swagger2
- add more examples under examples/openapi
=> add oas3 examples

bandit.yaml
Codacy issues warning when the `assert` keyword is used.
The concern from the bandit linter is that people might use `assert` in production code as a way of checking function inputs or something (no idea why anyone would ever do this).
In the case of connexion, it spews warnings any time you add a unit test! This is pretty annoying, and gives a false sense of a PR's code quality.
This PR disables that warning.
=> Codacy skip assert warnings

bandit.yaml
The `assert` keyword is used in unit tests, but codacy flags this as an error.
This results in bad codacy grades for PRs that add unit tests.
- skip codacy warning/errors from using the `assert` keyword
=> skip codacy warnings about the use of assert in unit tests

connexion/utils.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/fakeapi/aiohttp_handlers_async_def.py, tests/fixtures/aiohttp/swagger_simple_async_def.yaml
Fixed coroutinefunction verification when has async def.
It is necessary because there's no @asyncio.coroutine decorator to validate
Fixes # .
-
-
-
=> fix on utils.has_coroutine function

connexion/decorators/validation.py, tests/decorators/test_uri_parsing.py, tests/decorators/test_validation.py
Closes #439 
Add `x-nullable` support in properties by adding property validator to default `Draft4Validator`. It skips null-property with `"x-nullable": true` and then adds it back.
=> Add x-nullable support for body validators

README.rst
- simple fix of "Crafting effective Microservices in Python" url, as current link is dead
=> fix "Crafting effective Microservices in Python" blog post url

connexion/apis/aiohttp_api.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/fakeapi/aiohttp_handlers.py, tests/fixtures/aiohttp/swagger_simple.yaml
Fixes #696 .
- do not join query parameters values with `,` for AioHttpApi. `connexion.decorators.uri_parsing.AbstractURIParser` requires those to be an array, given the code (i.e. `{'queryParam': ['aValue']}`). However the dictionary that reaches the parses always have single string as value for each key.
=> Fix bad parsing of query params for AioHttp

setup.py
Fixes #707
- ensure jsonschema version is `< 3.0.0` in setup.py
=> set jsonschema max version

examples/sqlalchemy/app.py
disable threading in sqlalchemy demo because it uses an in-memory database, which is not shared across threads.
Fixes #706 
- disable threading in sqlalchemy demo
=> disable threading in sqlalchemy demo (in-memory db)

connexion/apis/abstract.py, tests/api/test_secure_api.py, tests/conftest.py
bugfix: get securitySchemes in openapi 3 APIs
Fixes #711 
Extracts just the bugfix from #703 
Thanks @cziebuhr
- include securitySchemes in self.security_definitions
- ensures test runs on both swagger 2 and openapi 3
=> bugfix: get securitySchemes in openapi 3 APIs (thanks @cziebuhr)

README.rst
Fixes #742 
- update docs to pass swagger_ui in options instead of kwargs
=> swagger-ui README section passes options instead of kwargs

connexion/operations/abstract.py, tests/fakeapi/hello.py
Fixes #750 
- pass file if filename in arguments _or_ has_kwargs
=> pass files to handler if filename in arguments _or_ has_kwargs

connexion/apps/abstract.py, connexion/apps/flask_app.py
Fixes #645 
@paulkernstock can you verify that this fixes your problem?
=> remove type hint for options in App.run(...)

docs/quickstart.rst
=> Use `/` instead of `\`

docs/request.rst
=> `collectionFormat` doesn't need the `'`

docs/security.rst
Fix not working link to example in JWT docs.
=> Fix link to example in JWT docs

connexion/apis/abstract.py, connexion/operations/__init__.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/spec.py, tests/test_api.py
Follow up to #713 
- Introduce make_operation that creates the correct Operation class from a Specification
- Move Specification classes to separate file (spec.py)
=> simplify Operation class construction

.travis.yml, setup.py, tox.ini
- Run travis on python 3.7.
- Use `Xenial` to run tests ([python 3.7 is incompatible with trusty](https://github.com/travis-ci/travis-ci/issues/9831)).
- Bump  `PyYaml` to earliest version with python 3.7 support.
=> Run travis on python 3.7

connexion/operations/openapi.py, tests/api/test_parameters.py, tests/fakeapi/hello.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Currently when object is send as body parameter only properties defined in `properties` in body schema are passed to handler function. Additional keys are filtered out, which is opposite to [spec](https://github.com/OAI/OpenAPI-Specification/blame/3.0.2/versions/3.0.2.md#L2305). For me specification is counter intuitive :(
- If `additionalProperties` is not set or is `True`, all properties not defined in `properties` are passed without type casting.
- If `additionalProperties` declares value type,  unknown properties are cast according to https://github.com/zalando/connexion#type-casting.
The best explanation for `additionalProperties` I found in https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-218829120
=> Fix handling additionalProperties in body

docs/index.rst
To celebrate the third birthday of OpenAPI, lets stop talking about Swagger. :)
=> OpenAPI > Swagger

connexion/decorators/validation.py, tests/decorators/test_validation.py
Fixes #811 
- use 'schema' in param_defn if available in validate_parameter(...)
=> fix openapi3 path and query validation and tests

connexion/apis/abstract.py, connexion/http_facts.py, tests/api/test_bootstrap.py, tests/fakeapi/hello.py, tests/fixtures/simple/openapi.yaml
hi,
First thing, thank you for creating and maintaining connexion !
this pull request allows to use [all path item fields](https://swagger.io/specification/#pathItemObject).
I encountered an error while creating an extension using **x-** vars in path object.  
The code was skipping only the field **Parameters** and tried to create an operation on others fields.
```
def test_using_all_fields_in_path_item(simple_api_spec_dir):
app = App(__name__, specification_dir=simple_api_spec_dir)
>       app.add_api('openapi.yaml')
tests/api/test_bootstrap.py:243: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.local/share/virtualenvs/connexion-LpTILqQi/lib/python3.6/site-packages/connexion/apps/flask_app.py:54: in add_api
api = super(FlaskApp, …
```
=> add path to API only for HTTP operations

requirements-aiohttp.txt, setup.py
Fixes master
Master is broken because of an aiohttp update upstream:
https://travis-ci.org/zalando/connexion/builds/469438675
- add an upper bound on the aiohttp version (<3.5.2)
I want to confirm that this fixes the build, and then we can investigate how to support the newest version.
=> set max aiohttp version to 3.5.1 (until build is fixed)

tox.ini
Attempts to fix the build.
Another attempt is #866 
Long story short, it looks like Flake8 now requires you to import anything mentioned in a type hint comment. This is extra annoying to reconcile across python versions. Hopefully they will resolve this upstream.
- Pin Flake8 to avoid nonsense in new version
=> Pin flake8 to avoid needing to import any types mentioned in type hints

connexion/apis/aiohttp_api.py, connexion/apps/aiohttp_app.py
[debug argument is deprecated](https://github.com/aio-libs/aiohttp/issues/2859) for AioHttp.
Remove it to remove deprecation warnings in logs.
=> Remove AioHttp deprecation warning

docs/security.rst, examples/openapi3/apikey/README.rst, examples/openapi3/apikey/app.py, examples/openapi3/apikey/openapi.yaml
Fixes a documentation link issue. The basic auth example link was under the api key example docs. This PR also implements an example for apiKey security scheme.
One question though (there are TODOs in the code I would like to update), the Connexion docs state that the `x-apikeyInfoFunc` method takes two parameters, `apikey` and `required scopes`. In testing, the required scopes are always None, and after looking at the openapi spec (https://swagger.io/docs/specification/authentication/#scopes) it appears that scopes are not used for the api key scheme.
Should the `x-apikeyInfoFunc` method not take in a `required_scopes` arg?
=> fixes basic auth example doc; adds apikey example

connexion/__init__.py, connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/cli.py, connexion/decorators/security.py, connexion/operations/__init__.py, connexion/operations/abstract.py, tests/aiohttp/test_aiohttp_api_secure.py, tests/aiohttp/test_aiohttp_app.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/api/test_bootstrap.py, tests/conftest.py, tests/decorators/test_parameter.py, tests/decorators/test_security.py, tests/decorators/test_uri_parsing.py, tests/decorators/test_validation.py, tests/fakeapi/__init__.py, tests/test_api.py, tests/test_cli.py, tests/test_json_validation.py, tests/test_metrics.py, tests/test_operation2.py, tests/test_references.py, tests/test_resolver.py, tests/test_utils.py, tests/test_validation.py, tox.ini
Fixes the build.
- apply all of the isort changes that resulted from the latest version
- pin to the latest version (4.3.15) so this doesn't happen again, unless we bump the version on purpose
=> bump and pin isort, apply all automatic fixes

connexion/apis/aiohttp_api.py, setup.py, tests/aiohttp/test_aiohttp_errors.py, tox.ini
AioHttp is not responding with problems yet. This uses an aiohttp middleware to handle exceptions and return a problem response.
Done:
Open questions:
- Do any docs need to change?
- This is just bringing AioHTTP exception handling into line with current Flask exception handling.
- https://connexion.readthedocs.io/en/latest/exceptions.html is out of date: https://github.com/zalando/connexion/blob/master/docs/exceptions.rst
- https://connexion.readthedocs.io/en/latest/response.html#error-handling also out of date (raise is better): https://github.com/zalando/connexion/blob/master/docs/response.rst
- There are essentially NO docs on aiohttp except for a brief reference here: https://github.com/zalando/connexion/blob/6bf058f6b7c20d87537eaa8bb3f701f69b383765/docs/quickstart.rst#L86-L93 …
=> Respond with problems by default in aiohttp.

setup.py, tests/decorators/test_security.py
Fixes #991 .
- bump `flask` to be at least `1.0.4`
Reasons:
- `flask==0.10.1` was released in 2013, which makes it quite old thus unsupported.
- On Flask webpage you can find an information pointing to `1.x` branch as latest stable
- different tools, including these used in `connexion` progressed leaving Python versions, for which `flask<1.0` has been developed.
=> Bump flask to be at least 1.0.4

docs/request.rst
Fixes #929
There was no documentation about preventing naming collisions between parameter names and python built-ins with the `pythonic_params` option.
=> Mention pythonic_params in request docs

tox.ini
Fixes (none).
- remove minor warning in travis output, apparently `[tox:travis]` is deprecated in favor of `[travis]`
From travis logs:
```The [tox:travis] section is deprecated in favor of the "python" key of the [travis] section.```
=> Fix travis deprecation

connexion/decorators/validation.py, tests/test_validation.py
Right now, based on following definition, parameters passed as cookies will not be validated.
```yml
name: token
in: cookie
description: token to be passed as a cookie
required: true
schema:
type: array
items:
type: string
```
Proposed change validate parameters stored in cookies in similar manner that we validate parameters passed in headers.
=> Add validation of cookie parameters.

README.rst, docs/request.rst
- Fixes a small typo in the documentation (`request.rst`) and in the `README.md` where `connexion` was typed as `connextion`.
=> Fixed [connextion] typo in documentation page

requirements-aiohttp.txt, setup.py, tests/test_cli.py
Fix test_run_with_aiohttp_not_installed with aiohttp 3.5.2+.
The error was prevented by requiring `aiohttp<3.5.2` in #844.
Somewhere between 3.5.1 and 3.5.2, this aiohttp reimport started succeeding.
I used pycharm's debugger to determine that it is this import that was successfully re-importing aiohttp.
https://github.com/zalando/connexion/blob/ff3adb393c67dea51a735ef3211794084db3623e/connexion/cli.py#L151-L155
It's not clear which change caused the issue, but I would guess one of these:
- aio-libs/aiohttp#3469 (Remove wildcard imports)
- aio-libs/aiohttp#3464 (Don't suppress gunicorn cleanup errors)
- aio-libs/aiohttp#3471 (Refactor workers)
- aio-libs/aiohttp#3500 (Ignore done tasks)
- Revert #844 
- Also set `sys.modules['aiohttp'] = None` in the …
=> Fix aiohttp upgrade

connexion/utils.py, tests/test_utils.py
The example below will seem strange. It's the result of distilling a complex
API spec down to the root cause of the issue.
```yaml
---
openapi: 3.0.0
info:
version: v0
title: Repo an error
description: Extremely contrived, but it illustrates the problem
paths:
/:
get:
operationId: app.get
responses:
'200':
description: Just for giggles
content:
application/json:
schema:
$ref: "#/components/schemas/SomeWeirdResource"
components:
schemas:
Resource:
allOf:
- type: object
properties:
id:
type: string
SomeWeirdResource:
allOf:
- type: object
properties:
id:
$ref: '#/components/schemas/Resource/allOf/0/properties/id'
```
While convoluted, this is a valid OpenAPI 3 spec.
```sh
$ yarn swagger-cli validate openapi/my_api.yaml
yarn run v1.17.3
$ /[redacted]/node_modules/.bin/swagger-cli validate …
```
=> Fixes util.deep_get when obj is a list

connexion/decorators/validation.py, setup.py
Fixes #983.
Other projects have started using jsonschema >= 3.0.0, and modern python packaging tools such as poetry now fail to install projects using both connexion and a different dependency if they depend on different versions of jsonschema.
Allow jsonschema versions >= 3.0.0 to avoid this problem. Add a version branch to avoid a warning that would otherwise be thrown by jsonschema when using the deprecated `types` parameter of the jsonschema.IValidator constructor.
- setup.py: Support jsonschema >= 3.0.0
- Avoid warning when using jsonschema >= 3.0
=> Support jsonschema >= 3.0.0

docs/security.rst
Hi, this is a minor change to the documentation which explains what to do in what I believe to be a potentially quite common use case - dealing with authentication with the production code deployed using flask and Apache.
- brief addition to security.rst referring readers to relevant modwsgi documentation.
=> Instructions for deploying on modwsgi

connexion/__init__.py, connexion/apis/aiohttp_api.py, connexion/apps/abstract.py, connexion/apps/flask_app.py, connexion/decorators/metrics.py, connexion/decorators/response.py, connexion/decorators/validation.py, connexion/exceptions.py, connexion/handlers.py, connexion/utils.py, requirements-all.txt, tests/aiohttp/test_aiohttp_errors.py, tests/fakeapi/hello.py, tests/test_metrics.py, tests/test_validation.py
The goal of this to convert all possible error responses to be a raised ProblemException subclass instead. Also for flask, allow for the option to skip the error handling.
The goal is to allow the end application handle the exceptions, as well as customize the response  that aligns with the application's payload structure.
=>  Converting response to raise a ProblemException

connexion/decorators/validation.py, tests/api/test_schema.py
Fixes #594 .
Fixes https://github.com/zalando/connexion/pull/816 
--> it gives `TypeError` when your json includes a list (the exception.path includes an integer )(TypeError: sequence item 1: expected str instance, int found)
--> Put 'path' at the end of the error message as it can sometimes be empty
- include json key with full path into validation error message
=> #594 & #816 - Add error path to schema validation error in RequestBodyValidator

.travis.yml, README.rst, connexion/decorators/decorator.py, connexion/decorators/response.py, connexion/mock.py, connexion/utils.py, docs/quickstart.rst, py2-coveragerc, setup.py, tests/test_mock.py, tox.ini
Partially #998 
- removed 2.7 from classifiers
- removed all references to 2.7
- code cleanup
=> Drop Python 2.7 support

connexion/json_schema.py
- import from `collections.abc` to support Python 3.8
- fallback to import from `collections` if `collections.abc` is not available
=> Import from collections.abc to support Python 3.8

setup.py
This is a follow up for c8d8973c7e390a5e2071c7b494dd7bd52bd55ff1
(dropping Python 3.5). There were some leftovers in requirements for
Pythonv versions `connexion` no longer supports.
=> Clean up dropping Python 3.{4,5}

connexion/operations/abstract.py, tests/api/test_parameters.py, tests/fakeapi/hello.py
=> Fixes #510: Multiple file uploads via POST now work correctly.

connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/options.py, docs/quickstart.rst, tests/aiohttp/test_aiohttp_simple_api.py, tests/api/test_bootstrap.py
Fixes #841 by add an option `swagger_ui_config` to pass config parameters to the Swagger UI . 
This is done by providing a `swagger-ui-config.json` endpoint with the contents of the `swagger_ui_config` option. This file is then referenced via the `configUrl` parameter in the Swagger UI `index.j2` template.
- Add `swagger_ui_config` option  to pass config parameters to the Swagger UI
=> Add swagger_ui_config option to pass config to the Swagger UI

tests/aiohttp/test_aiohttp_app.py, tests/test_api.py
These five unit tests were failing under Windows due to differences in OS behavior.
The three tests in tests/test_api.py were failing since the NamedTemporaryFile object cannot be opened more than one time on Windows.  
The two tests in tests/aiohttp/test_aiohttp_app.py were failing due to hard-coded '/' path separator.
=> Fix unit tests on Windows

connexion/apis/flask_api.py
- Fix return type docstring in `connexion.apis.flask_api.FlaskApi.get_response` so editors/IDEs don't raise warnings when type hinting
=> Fix return type docstring for get_response

connexion/decorators/uri_parsing.py, tests/fakeapi/hello.py, tests/fixtures/json_validation/openapi.yaml, tests/test_json_validation.py
adding support to automatically decode json when a multipart/form-data request body contains a field with an application/json content-type
Fixes #935.
Fills in a decode step where there's already a TODO (I think) saying it needs to be done for a variety of types.
=> [#935] supporting application/json within multipart/form-data request body

.gitignore, connexion/apis/abstract.py, connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/jsonifier.py, connexion/utils.py, examples/openapi3/helloworld_aiohttp/README.rst, examples/openapi3/helloworld_aiohttp/hello.py, examples/openapi3/helloworld_aiohttp/openapi/helloworld-api.yaml, requirements-aiohttp.txt, setup.py, tests/aiohttp/test_aiohttp_api_secure.py, tests/aiohttp/test_aiohttp_datetime.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/conftest.py, tests/fakeapi/aiohttp_handlers.py, tests/fakeapi/hello.py, tests/fixtures/aiohttp/datetime_support.yaml, tests/fixtures/datetime_support/openapi.yaml, tests/fixtures/datetime_support/swagger.yaml, tests/test_flask_encoder.py
Fixes #846 .
- Add date, datetime and uuid serialization for AioHttp
- Use JSonifier to serialize all data in AioHttp
- Move Jsonifier in its own file for easier extension
- Remove ujson dependency: Flask use json from itsdangerous, [ujson does not support custom types](#124) for AioHttp.
=> Datetime serialization

docs/security.rst
Fixes documentation error found in OAuth section: https://connexion.readthedocs.io/en/latest/security.html#apikey-authentication
- Change minimal API key example link, (currently broken) to the location the example was found at: https://github.com/zalando/connexion/blob/master/examples/openapi3/apikey/app.py
=> Updated API Key example link to correct location

connexion/apps/abstract.py, tests/test_app.py
Fixes #1083 
- use `None` as default value for `debug` parameter in `AbstractApp` to allow users to use flask environment variables to activate debug mode
=> Allow users to enable debug mode via environment variables

connexion/cli.py
- It appears the mockmode metavar is unused in code. Please correct me if I am wrong.
- The problem it causes by being there is it overrides the default --help` string from `connexion run --help` so that it is difficult to understand what the possible arguments are for `--mock`. From reading the `click` docs & code, it seems that if we leave the metavar out, it will correctly populate the available options.
=> Remove unused metavar

connexion/apps/aiohttp_app.py, tests/aiohttp/test_aiohttp_app.py
- The `**options` arguments the [`AioHttpApp.run`](https://github.com/zalando/connexion/blob/master/connexion/apps/aiohttp_app.py#L71) method are not forwarded to the [`run_app`](https://github.com/zalando/connexion/blob/master/connexion/apps/aiohttp_app.py#L93) method of the `aiohttp` framework. It is analogous to what is done here: https://github.com/zalando/connexion/blob/master/connexion/apps/flask_app.py#L93, but for the `flask` framework.
=> Forward options to the AioHTTP app.

connexion/decorators/security.py, tests/fakeapi/hello.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Fixes:
Fixes Bad Request error when ApiKey authentication is used with the apiKey query parameter, and strict validation is enabled.
The corresponding open issue is https://github.com/zalando/connexion/issues/470.
- Pop apiKey from the query parameters before validation.
=> Pop apiKey from query parameters in security decorator to fix #470

.gitignore, connexion/apis/abstract.py, connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/jsonifier.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/aiohttp/test_get_response.py, tests/api/test_responses.py, tests/conftest.py, tests/fakeapi/aiohttp_handlers.py
First step of #828
- Support tuples as return values for aiohttp handlers
=> Return tuple for aiohttp

tests/aiohttp/test_aiohttp_app.py
Fixes #1097 
- don't check that the repo is cloned into "connexion" directory
=> Fix test that relies on the repo folder being named Connexion

connexion/operations/abstract.py, tests/api/test_parameters.py, tests/fakeapi/hello.py
Reverts zalando/connexion#1000
This break aiohttp because getlist() is specific to a werkzeug datastructure.
=> Revert "Fixes #510: Multiple file uploads via POST now work correctly."

tests/fixtures/simple/openapi.yaml
This includes assorted fixes to bring the "simple" test schema in line with OpenAPI 3.0.
These issues were identified by attempting to validate the schema against [the OpenAPI schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json) using [jsonschema](https://github.com/Julian/jsonschema).
=> Test schema corrections

connexion/__init__.py, connexion/apis/abstract.py, connexion/apis/flask_api.py, connexion/apps/abstract.py, connexion/decorators/parameter.py, connexion/decorators/security.py, connexion/decorators/uri_parsing.py, connexion/decorators/validation.py, connexion/jsonifier.py, connexion/operations/abstract.py, connexion/spec.py, connexion/utils.py, requirements-devel.txt, setup.py
Remove `six` usage, i.e. remove Python 2 support.
=> Remove six (Python 2 support)

connexion/__init__.py, connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/spec.py, examples/openapi3/reverseproxy/README.rst, examples/openapi3/reverseproxy/app.py, examples/openapi3/reverseproxy/openapi.yaml, examples/openapi3/reverseproxy_aiohttp/README.rst, examples/openapi3/reverseproxy_aiohttp/app.py, examples/openapi3/reverseproxy_aiohttp/nginx.conf, examples/openapi3/reverseproxy_aiohttp/openapi.yaml, setup.py, tests/aiohttp/test_aiohttp_reverse_proxy.py, tests/api/test_responses.py, tests/conftest.py
Fixes #820 
Fixes #392 
Fixes #527 
- change swagger-ui, and openapi spec location to build the path using `url_for`
- modify the openapi spec `basePath` or `servers` block to include the reversed api path
- modify the swagger-ui page to load the reversed openapi spec using `url_for`
- add a openapi3/reverseproxy example
- add a openapi3/reverseproxy_aiohttp example
Thanks to @Jyhess for the collaboration, tests, and review!
=> Serve correct openapi spec basepath when path is altered by reverse-proxy

setup.py
Pip installing connection in a py2.7 env pulls in unsupported 2.5.0
This PR updates connextion to only allow installation on python >= 3.6
If merged, this PR should fix:
https://github.com/zalando/connexion/issues/1108
=> Don't allow connexion installation in py27

connexion/apps/aiohttp_app.py, tests/aiohttp/test_aiohttp_app.py
- Pop access_log option from aiohttp options
- Add test to access_log options in aiohttp run
=> Fix: aiohttp access_log duplicated if passed as argument

connexion/decorators/security.py, connexion/operations/secure.py, tests/api/test_secure_api.py, tests/fakeapi/hello.py, tests/fixtures/secure_endpoint/openapi.yaml, tests/fixtures/secure_endpoint/swagger.yaml
This allows to use optional authentication and provide different
responses to authenticated users via the same API-Endpoint.
Fixes #1036
- Enable optimal authentication
- Provide different information to logged in customers via the same API endpoint
=> enable empty security definition

tests/aiohttp/test_aiohttp_datetime.py, tests/test_flask_encoder.py
Fixes Master, which is broken due to PyYAML change in 5.3
https://github.com/yaml/pyyaml/pull/163
- update test to not expect `Zulu` datetime ending, as PyYAML 5.3 parses the date as TZ aware
=> Fixes Build: Allow new datetime behavior in PyYAML 5.3

connexion/operations/abstract.py, tests/aiohttp/test_aiohttp_datetime.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/fakeapi/aiohttp_handlers.py, tests/fixtures/aiohttp/openapi_simple.yaml, tests/test_flask_encoder.py
=> fix pythonic path param types in aiohttp

connexion/decorators/uri_parsing.py, connexion/operations/openapi.py, connexion/utils.py, tests/api/test_parameters.py
Fixes spread of defaults into other parameters
Redo #971 
Fixes #1092 
Fixes #1082 
- scope deepObject code to openapi3-only code blocks (defaults do not belong in uri_parsing, nor does deepObject logic make sense in an AbstractURIParser)
- fix set_default_values(...) which put defaults from any parameter type into all other parameters.
Future:
- modify testing fixtures to catch setting request.form, request.files, request.body etc unintentionally
=> scope deepObject defaults code to query params only 

connexion/decorators/validation.py, tests/api/test_parameters.py
blocked by:
#1125 
#1110 
When using an OAS3 spec with formdata, the validation logic looks
for the key 'formData' in the spec parameters list. This keys is
specific to OAS2, and will never be present, causing any form data to
throw an ExtraParameterProblem.
Fixes #1020 
- Don't fail strict validation if `formData` key is missing from the spec parameters (this is expected in OAS3)
=> Fixes #1020, OAS3 false positive for extra form param

connexion/decorators/uri_parsing.py, tests/api/test_responses.py
Fixes #1129  .
- inside of a exploded `deepObject`, the keys can be any character. Especially dots need to be allowed. sanitation does not apply, because it will result in an object key, not a python var name.
=> match all but whitespaces inside object keys

docs/routing.rst
Addresses request by @hjacobs here: https://github.com/zalando/connexion/issues/1115#issuecomment-571206789
- Document how and why to use `resolver_error` configuration
=> add documentation regarding resolver_errors

connexion/operations/openapi.py, tests/api/test_responses.py, tests/fakeapi/hello.py, tests/fixtures/simple/openapi.yaml
Fixes #1137 
Redo #971
- Don't drop nested additionalProperties
- Remove unnecessary filtering of objects in OAS3 (if it passed validation, it can be used as-is)
=> fix nested additionalProperties

connexion/operations/openapi.py, connexion/operations/swagger2.py, tests/test_mock.py
Objects and Arrays recursively construct examples from examples of their children
Fixes #409 .
- In MockResolver, Objects and Arrays recursively construct examples from examples of their children
- Extra tests in test_mock.py
=> Objects and Arrays recursively construct examples

connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py
There is a small typo in connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py.
Should read `parsing` rather than `parseing`.
=> docs: Fix simple typo, parseing -> parsing

docs/request.rst
The `uri_parsing_class` option presented in the docs does not exist. It took me some time to figure out that the name of this option is actually `uri_parser_class`.
- Correct `uri_parsing_class` to `uri_parser_class` in docs example.
=> Fixed spelling of uri_parser_class in code example

setup.py, tests/api/test_bootstrap.py, tests/decorators/test_parameter.py, tests/decorators/test_security.py, tests/decorators/test_validation.py, tests/test_api.py, tests/test_cli.py, tests/test_metrics.py, tests/test_operation2.py, tests/test_references.py, tests/test_utils.py, tests/test_validation.py
Since you dropped python 2.7 support, a switch from mock to unittest.mock is possible. The switch is done in this pull request.
By the way:
I made a request for packaging connexion-2.6.0 for debian unstable and already submitted a package. If you are interested in it, have a look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958042
=> Switched from mock to unittest.mock

connexion/apis/aiohttp_api.py, tests/aiohttp/test_get_response.py
Returning a `aiohttp` `StreamResponse` (and probably `FileResponse`) was failing the `AioHttpApi._framework_to_connexion_response` made the assumption that the `response` object had a body, which is not the case for `StreamResponse` and `FileResponse`
- We now check if the `response` given to `_framework_to_connexion_response` has a `body` attribute and default to a `None` body otherwise
- I prefered to use: 
```python
if hasattr(response, "body"):
body = response.body
```
rather than:
```python
if isinstance(response, web.Reponse):
body = response.body
```
in prevision of the unlike case where `aiohttp` would add another `web.StreamResponse` sublcass without body
=> Fix _framework_to_connexion_response for StreamResponse

docs/security.rst
Fixes #1188
- Add note that protected handler functions accepting `token_info` will be passed the full token info response in that argument.
=> Document token_info argument

docs/security.rst
Changed `of` to an `or`, I guessed a Dutch person wrote this and noticed it's one of the biggest gotchas to see if a Dutchie is the author.
Fixes # .
There is a type in the document where an or should replace the of.
- Change "For example, an `x-tokenInfoFunc` of `auth.verifyToken` would pass..." to "For example, an `x-tokenInfoFunc` or `auth.verifyToken` would pass..."
=> Fix typo in security.rst from of to an or

connexion/apps/abstract.py, connexion/apps/aiohttp_app.py, connexion/apps/flask_app.py
Fixes # .
Changed AbstractApp constructor so to accept Flask server args
Changed create_app to pass Flask server args to Flask constructor
-
-
-
=> Added server_args to AbstractApp

connexion/apis/aiohttp_api.py, examples/openapi3/helloworld_aiohttp/hello.py, tests/aiohttp/test_get_response.py, tests/fakeapi/aiohttp_handlers.py
Fixes #1182 .
- replaced `@asyncio.coroutine` and `yield from` with `async` and `await` respectively
=> Python 3.8: replace @asyncio.coroutine/yield from with async/await #1182

connexion/resolver.py
- router_controller has already been access before the if state, so we can just reuse it
=> avoid unnecessary object attribute lookup

connexion/decorators/validation.py, tests/decorators/test_validation.py
When specifying array of enum strings in header,
it needs to be split according to commas.
Fixes #1278.
- When header is of type array, split the string by comma before validating
=> Split header by comma

docs/routing.rst
- Add a note about x-openapi-router-controller when using OAS
Fantastic work, this repo is. There are quite a few confusions out on the interwebs about the RestyResolver, one of which I stumbled on when using OpenAPI 3. A simple docs update should help others not spin their wheels on this like I did.
=> Add note about x-openapi-router-controller when using OAS

setup.py
Fixes #1149.
- add explicit werkzeug dependency
- set lower version bound to 1.0 - I'm not sure if there are earlier versions that would break things.
- set upper version bound to 2.0 - Any breaking changes could be bad.
=> Add explicit werkzeug dependency

connexion/decorators/response.py, connexion/decorators/validation.py
The default value of _ResponseBodyValidator.validator_ is not _jsonschema.Draft4Validator_ for some time already. It is _Draft4ResponseValidator_ now.
_ResponseValidator.validator_ does not have a default value. If not set, _ResponseBodyValidator_ default is used, which is eventually _Draft4ResponseValidator_, but it is not _ResponseValidator_ that decides it.
=> Fix response validator docstrings

README.rst
This PR updates the badges the reflect the change from `master` to `main`. (Also updated the link of the license badge).
See also #1369.
=> Update readme badges to use main branch

connexion/decorators/validation.py, tests/decorators/test_validation.py
Fixes #1020. Fixes #1160. Fixes #1340. Fixes #1343.
The previous fix which tries to catch a `KeyError` does not work since `self.parameters` is a `defaultdict`. Changed to an explicit `if` check instead.
=> Fix formdata parameter validation for OAS3

.github/workflows/pipeline.yml, tox.ini
=> GitHub Action: test on current version of Python

connexion/apis/flask_api.py, connexion/decorators/parameter.py, connexion/decorators/validation.py, connexion/options.py, connexion/spec.py, tox.ini
https://pypi.org/project/flake8
$ `./setup.py flake8`
```
running flake8
WARNING: flake8 setuptools integration is deprecated and
scheduled for removal in 4.x.  For more information, see 
```
https://gitlab.com/pycqa/flake8/issues/544
Fixes # .
-
-
-
=> tox.ini: flake8==3.9.2

examples/openapi3/reverseproxy/app.py
In the current example, the run() method is called on the app variable, which does not have its path altered.
This small PR updates app to flask_app to fix that problem.
=> Fix reverseproxy example for OpenAPI 3

connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/options.py
Fixes #1178  .
- add an app option for variables which will be passed to swagger-ui index.j2 template
=> expose swagger-ui index template variables to app configuration

.readthedocs.yaml, setup.py
Fixes #1390
https://docs.readthedocs.io/en/stable/faq.html#my-documentation-requires-additional-dependencies
=> Add readthedocs config with docs requirements

docs/cookbook.rst
Documents how "wildcard paths" are supported in Connexion. Closes #1397.
=> Document how to use a wildcard path parameter

connexion/apps/flask_app.py, tests/api/test_parameters.py, tests/fakeapi/hello/__init__.py
This change installs more liberal flask converters for `float` and `int`. These don't try to enforce a "single representation" of paths but instead try to convert the numbers that callers pass in.
This is the minimal change to get this effect and installs the custom number converters where the custom JSON converter is being installed already. An alternative would be to register the new converters as `integer` and `number` in Flask and update the `PATH_PARAMETER_CONVERTERS` mapping, but that's a larger change and would change the generated flask paths which could affect existing code.
Fixes #1040
Fixes #1041
The tests for numbers in paths are modified to return not just `int` or `float` but also the value seen by the handler so we can ascertain that the conversion works and not just the …
=> More liberal flask number converters for float and int in paths

MANIFEST.in
Fixes #1003 .
Just a small fix to remove the obsolete reference to vendor files in MANIFEST.in
=> Remove reference to deleted vendor files

connexion/apis/flask_api.py, connexion/options.py
Fixes #1289.
https://github.com/zalando/connexion/issues/1289#issuecomment-884105076 for more info.
I also included a commit which cleans up an unused constant which I noticed while debugging this issue.
=> Render correct template in API

MANIFEST.in, connexion/resources/schemas/v2.0/schema.json, connexion/resources/schemas/v3.0/schema.json, connexion/spec.py
Addresses #930.
- use jsonschema for validation instead of openapi_spec_validator
=> jsonschema validation

.github/workflows/pipeline.yml, tests/api/test_parameters.py, tox.ini
Related to #2, #998, #1111
Proves #1392
`mypy --exclude '/(__init__|api|api.pets|app|hello|orm|resty)\.py$' --install-types --non-interactive .`
- Run [`mypy`](https://mypy.readthedocs.io) in [tox ignore_outcome](https://tox.readthedocs.io/en/latest/config.html#conf-ignore_outcome) mode to show progress on #1111
- Making mypy work is a pain in the neck!!
```
tox: mypy
mypy run-test-pre: PYTHONHASHSEED='866419681'
mypy run-test: commands[0] | mypy --exclude '/(__init__|api|api.pets|app|hello|orm|resty)\.py$' \
--install-types --non-interactive .
tests/api/test_parameters.py:62: error: syntax error in type comment "[str] multi array with csv format"
tests/api/test_parameters.py:66: error: syntax error in type comment "[str] multi array with csv format" …
```
=> Tox.ini: Run mypy in ignore_outcome mode

connexion/decorators/parameter.py, tests/api/test_parameters.py, tests/fakeapi/snake_case.py, tests/fixtures/snake_case/openapi.yaml, tests/fixtures/snake_case/swagger.yaml
Fixes #1424 .
- Add Python's keywords to the list of reserved words for underscoring.
=> #1424: add keywords to the list of pythonic words

connexion/decorators/validation.py, tests/api/test_errors.py, tests/fixtures/problem/openapi.yaml, tests/fixtures/problem/swagger.yaml
As per the issue #1181 , the 415 response now is improved!
=> improved error 415

connexion/json_schema.py, connexion/spec.py, setup.py
Fixes #1430
- Drop usage of private jsonschema modules to prevent breaking on non-major version changes.
- Create validate_defaults function by passing in the instance_validator instead of using an attribute on the OpenApiValidator. This is necessary since the attribute is no longer maintained while the validator descends into the spec. I presume due to the usage of `attrs.resolve` by jsonschema.
=> Bump upperbound version for jsonschema to 5.0.0

connexion/decorators/parameter.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, tests/api/test_parameters.py, tests/fakeapi/hello/__init__.py, tests/fakeapi/snake_case.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/snake_case/openapi.yaml, tests/fixtures/snake_case/swagger.yaml
Fixes #1183.
- Only perform sanitization when checking the python view function arguments and move the parameter sanitization as much as possible to the same place
=> Fix sanitization of function arguments

connexion/apps/flask_app.py
Flask can automatically reload in debug mode whenver specified files
change. By default that includes templates, however changes to the API
files (i.e. openapi.yml) should result in a reload as well.
This PR adds all added API files to be monitored automatically by Flask.
WIP since I have to figure out the used `tox` setup first.
Signed-off-by: Paul Spooren <mail@aparcar.org>
=> Reload Flask on API file changes

docs/conf.py
The generated API reference documentation only used the class docstring, this PR changes this such that both the class docstring and the `__init__` docstring are used [1]. For example, the `FlaskApp` and `AbstractApp` only contain documentation in the init methods.
[1] https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_python_class_content
Before: https://connexion.readthedocs.io/en/stable/autoapi/connexion/apps/flask_app/index.html#connexion.apps.flask_app.FlaskApp
After: https://connexion--1451.org.readthedocs.build/en/1451/autoapi/connexion/apps/flask_app/index.html#connexion.apps.flask_app.FlaskApp
=> Use both class docstring and init docstring for autoapi

connexion/decorators/parameter.py, connexion/decorators/uri_parsing.py, tests/decorators/test_uri_parsing.py
Fixes # . 
Fix square bracket in query params. Example : `orderBy[eq]`.
Its a quick fix to permit square bracket in query params, if they are define in the schema.
For query params who are not in the schema. Do default computation for deep object.
- Modify `sanitized` function to replace `[` by `_`. Example : `orderBy[eq] -> order_by_eq`
- Modify `_make_deep_object` function to use key with square bracket in the name as a dict key if its define in the schema
=> fix-square bracket : V1

.github/workflows/release.yml
[The test release pipeline failed](https://github.com/spec-first/connexion/actions/runs/1809057983) after merging #1454 because you can only upload a package on PyPi with the same version once.
This PR changes the trigger for the test release pipeline to tags, so it only runs when there's a new version.
This way, releasing works as follows:
1. Push tag
2. Test release pipeline
3. Publish release
4. Release pipeline
=> Change test release trigger to tags

.github/workflows/release.yml
Last time hopefully :)
The release pipeline fails because we're uploading the same version to TestPyPi both in the test pipeline (on push of tag) and on the release pipeline (when publishing the github release). This PR skips publishing to TestPyPi in the actual release pipeline.
After this is merged, I'll move the 2.11.0 tag to the merge commit. The triggered test pipeline will fail (because it will try to upload 2.11.0 again), but the release pipeline should succeed.
=> Only push to TestPyPi on tag trigger

setup.py
This PR updates our `setup.py` to correctly indicate support for Python 3.9 which we're already using as target version in our test pipeline.
=> Add Python 3.9 to supported versions in setup.py

connexion/apis/aiohttp_api.py
Change `aiohttp` `req.has_body` to `req.can_read_body`. Fixes #1136.
- Support for `aiohttp 4.x` (which is the default installation version), where `req.has_body` is no longer supported ([ref](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.has_body)).
=> Change deprecated aiohttp req.has_body to req.can_read_body

connexion/json_schema.py, connexion/spec.py, tests/fakeapi/hello/__init__.py, tests/fixtures/json_validation/openapi.yaml, tests/fixtures/json_validation/swagger.yaml, tests/test_json_validation.py
=> Take into account (x-)nullable when validating defaults

connexion/apis/flask_api.py, connexion/decorators/response.py, connexion/lifecycle.py, tests/api/test_responses.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
prior to validation get_connexion_response ultimately calls response.get_data()
I haven't found a workaround for this and the old PR was closed due to inactivity.
I changed it to use getattr as the object may not be a response (could be tuple).
Fixes #904 .
there are also a few other issues raised.
- bypass for response.is_streamed, otherwise no change in behaviour
-
-
=> Don't validate streamed responses

setup.py
To prevent a dependency conflict between Flask and itsdangerous.
See https://github.com/pallets/flask/issues/4455
=> Bump Flask lower bound to 1.1.4

connexion/json_schema.py, setup.py, tests/api/test_bootstrap.py
Fixes #930 
Continues on #936 
This PR completely removes the dependency on `openapi-spec-validator`. There's multiple reasons to do this:
- One dependency less
- We don't use `openapi-spec-validator` for it's main purpose, but for utility functionality
- It's not production ready (https://github.com/p1c2u/openapi-schema-validator/issues/31#issuecomment-1014141023)
- We recently had some issues with dependency conflicts (https://github.com/spec-first/connexion/issues/1430#issuecomment-1007737974)
=> Drop openapi-spec-validator for custom ref handler

connexion/operations/openapi.py
This was introduced in #1222. 
We should not sanitize the body schema, since we don't sanitize body arguments. This creates a mismatch when comparing both.
=> Remove sanitization of body properties

connexion/resolver.py, tests/fakeapi/__init__.py, tests/fakeapi/example_method_view.py, tests/test_resolver_methodview.py
Fixes #1466 .
dependent on #1465 
- change `view_name` to be `CamelCase` instead of a mix of CamelCase and snake_case.
- update tests to output CamelCase for MethodViewResolver
=> [FIX] MethodViewResolver CamelCase Methods

connexion/apis/aiohttp_api.py, connexion/apis/flask_api.py, connexion/lifecycle.py, tests/aiohttp/test_aiohttp_simple_api.py, tests/api/test_parameters.py, tests/fakeapi/aiohttp_handlers.py, tests/fakeapi/hello/__init__.py, tests/fixtures/aiohttp/openapi_simple.yaml, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Fixes #1168.
- Add a `cookies` attribute to `lifecycle.ConnexionRequest`
- Use `flask.Request.cookies` and `aiohttp.web.Request.cookies`
=> lifecycle: add cookies attribute to ConnexionRequest (#1168)

connexion/spec.py
Nodoby needs the schema strings vs. the parsed contents, yet those strings consume quite some memory for big specs.
=> Save memory on unused schema strings

docs/response.rst
Fixes #1483.
- Add link to Flask documentation for more info
=> Add link to Flask JSONEncoder documentation

docs/security.rst, examples/openapi3/basicauth/README.rst, examples/openapi3/basicauth/app.py, examples/swagger2/basicauth/README.rst, examples/swagger2/basicauth/app.py
Fixes #1471 / #1485
- Remove obsolete code (see the beginning of #1485 for concrete reasoning)
- Remove scopes completely except necessary arg in `x-basicInfoFunc` implementation
=> Remove obsolete code from basicauth example

.gitignore, connexion/operations/secure.py, connexion/security/async_security_handler_factory.py, connexion/security/security_handler_factory.py, docs/security.rst, tests/api/test_secure_api.py, tests/decorators/test_security.py, tests/test_operation2.py
Fixes #1423  .
Moves the required_scopes argument as current approach assumes there is one possible set of scopes per operation/security object.
I have changed the tested behaviour for [this test](https://github.com/spec-first/connexion/blob/main/tests/api/test_secure_api.py#L99).
If there is optional auth, if an incorrect API key is provided, the `verify_none` still passes and given that the security schemes are specified in OR fashion, the security check should pass.
(For example, changing the security schemes around in the spec ([link](https://github.com/spec-first/connexion/blob/main/tests/fixtures/secure_endpoint/swagger.yaml#L169-L170)) also causes the test to fail, which shouldn't happen as the order shouldn't matter)
=> Rework required_scopes checking

connexion/decorators/validation.py, connexion/spec.py, setup.py
Fixes #1479 
- Use `importlib.resources` to retrieve schemas
- `read_text()` doesn't support files in directories, so we have to use the package name, but the package name was invalid due to the `.` in the directories, and also needed to add `__init__.py` files for it to work. 
We can also use the `files()` function, which does support subdirectories, but this would require the external package until Python 3.9
- Use `importlib.metadata` and `packaging` to retrieve, parse and compare versions
- This can be dropped once we bump the minimum version of `jsonschema` to `3`
=> Drop pkg_resources

connexion/apps/abstract.py, connexion/apps/flask_app.py, connexion/middleware/__init__.py, connexion/middleware/main.py, setup.py, tests/api/test_errors.py, tests/conftest.py, tests/fakeapi/hello/__init__.py
Part of #1489 
This PR adds the empty ConnexionMiddleware and wraps it around the FlaskApp using the `a2wsgi.WSGIMiddleware` adapter.
The ConnexionMiddleware and FlaskApp both implement the ASGI interface, and an ASGI server is the recommended way to run it. 
The `a2wsgi.ASGIMiddleware` adapter is wrapped around the ASGI middleware to make it WSGI compliant so it can be used by the development server and test client.
=> Add empty connexion middleware

connexion/decorators/parameter.py, tests/decorators/test_parameter.py
Fixes an issue where query parameters with empty brackets are not sanitized correctly.
In the example below, the `ids[]` parameter was sanitized to `ids_` since [this change](https://github.com/spec-first/connexion/pull/1408/files#diff-fdef5b8ce70b2c603bff264825d3b8baad76326f32a4e94455224f680f65b780L68-R68).
```yaml
parameters:
- name: ids[]
in: query
type: array
items: string
collectionFormat: multi
```
```Python
?ids[]=a&ids[]=b
```
This PR fixes the sanitization so it's `ids[]` becomes `ids`.
=> Fix uri parsing for query parameter with empty brackets

tests/api/test_headers.py
Cherry picks the fix for werkzeug 2.1 from main for our v2 branch.
https://github.com/pallets/werkzeug/issues/2352.
=> Update tests for changed werkzeug behavior in 2.1

connexion/apis/__init__.py, connexion/apis/abstract.py, connexion/apis/flask_api.py, connexion/apps/abstract.py, connexion/apps/flask_app.py, connexion/middleware/__init__.py, connexion/middleware/base.py, connexion/middleware/main.py, connexion/middleware/swagger_ui.py, tests/api/test_responses.py
Part of https://github.com/spec-first/connexion/issues/1489
This PR extracts the Swagger UI functionality into a middleware.
The middleware is implemented with a starlette router on which the swagger ui endpoints are registered. For all other routes, the router acts ass a pass-through.
=> Extract Swagger UI functionality into middleware

.pre-commit-config.yaml, README.rst, setup.py, tox.ini
This PR adds a pre-commit hook which runs the static analysis checks on the changed code before committing. The hook is reused by tox so the steps only need to be defined once.
This is a prerequisite for https://github.com/spec-first/connexion/issues/1498.
=> Add pre-commit hook

connexion/apis/__init__.py, connexion/apis/abstract.py, connexion/apps/abstract.py, connexion/apps/flask_app.py, connexion/exceptions.py, connexion/lifecycle.py, connexion/middleware/__init__.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/swagger_ui.py, tests/api/test_errors.py, tests/conftest.py, tests/fakeapi/auth.py, tests/test_middleware.py
Part of https://github.com/spec-first/connexion/issues/1489
This PR adds a routing middleware, which adds the connexion operation to the scope passed to the next middlewares.
The middleware is implemented with a starlette router on which the api endpoints are registered. For all other routes, the router acts ass a pass-through.
=> Add routing middleware

connexion/decorators/parameter.py, connexion/operations/openapi.py, tests/api/test_responses.py, tests/api/test_secure_api.py, tests/decorators/test_parameter.py, tests/fakeapi/auth.py, tests/fakeapi/hello/__init__.py, tests/fixtures/secure_endpoint/openapi.yaml, tests/fixtures/secure_endpoint/swagger.yaml, tests/fixtures/simple/openapi.yaml
This PR merges the fixes on the V2 branch to the main branch.
=> Merge V2 to main

connexion/spec.py, setup.py
Fixes #1510 
- Move from .iter_errors to .evolve().iter_errors to fix the deprecation warning
- Bump the earliest possible used version of jsonschema to v4.0.1 (v4.0.0 got yanked)
=> Fix deprecation warning for Validator.iter_errors

connexion/apis/__init__.py, connexion/apis/abstract.py, connexion/handlers.py, connexion/middleware/routing.py
This PR refactors the routing middleware into the middleware-api-operation model already used in the security middleware. 
This model is often used in the API community and should be a good basis for any middleware that needs to act on an operation level.
=> Refactor routing into middleware-api-operation model

connexion/operations/openapi.py, connexion/operations/swagger2.py, tests/test_mock.py, tests/test_mock3.py, tests/test_operation2.py, tests/test_resolver.py, tests/test_resolver3.py, tests/test_resolver_methodview.py
This PR does some additional cleanup of the operation classes after we migrated the security functionality to middleware in #1514. Cleaned up some additional unused code as well.
=> Clean up operation classes

connexion/decorators/validation.py, setup.py
Fixes #1537
- Remove jsonschema version checks
- Remove dependency on `importlib_metadata`
=> Removed jsonschema version check

connexion/apis/abstract.py, connexion/middleware/routing.py, connexion/middleware/security.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/spec.py
Continues on https://github.com/spec-first/connexion/pull/1514.
This PR continues the implementation of the security middleware, which was started in https://github.com/spec-first/connexion/pull/1514. I took some shortcuts in the original PR, one of them the naive 'resolution' of the `operation_id` by fetching it from the spec instead of relying on a resolver.
https://github.com/spec-first/connexion/blob/b561ecfdaacd7606d1398512762b946e2d778c74/connexion/middleware/security.py#L93
This PR replaces this with resolution via resolver.
You'll see that I rely on the original Connexion `Operation` classes for this, instead of on the `Resolver` directly. I propose to further hollow out the `Operation` classes during the refactoring into a middleware stack, until it becomes a 'data class' …
=> Use resolver in security middleware

connexion/resolver.py, docs/routing.rst, examples/openapi3/methodresolver/api/__init__.py, examples/openapi3/methodresolver/api/petsview.py, examples/openapi3/methodresolver/app.py, tests/conftest.py, tests/test_resolver_methodview.py
Signed-off-by: Nico Braun <rainbowstack@gmail.com>
Fixes #1549 
>**Warning** 
>this is a breaking change
> users will be required to change any search method to a get method, merging _get by id_ and _get collection_ into a single handler
The primary reason for this change is to be able to use method decorators as described here: https://flask.palletsprojects.com/en/2.1.x/views/#decorating-views
- change the `MethodResolver` to call `as_view` on the classes
=> call as_view in methodresolver

connexion/security/security_handler_factory.py, setup.py, tests/decorators/test_security.py
The async tests were getting skipped because we didn't have an appropriate pytest setup for it. This PR aims to fix this and adjusts the tests accordingly.
=> Fix async tests

connexion/resolver.py, tests/conftest.py, tests/fakeapi/__init__.py, tests/fakeapi/example_method_view.py, tests/fixtures/method_view/openapi.yaml, tests/fixtures/method_view/swagger.yaml, tests/test_resolver.py, tests/test_resolver_methodview.py
Follow up on #1552 
- Add test for `MethodViewResolver`. I had to rename some stuff to clean this up a bit.
- Add warning about ignoring `collection_endpoint_name` in `MethodViewResolver`
- Add format of `class_arguments` in docstring
CC: @bluebrown
=> Add test for MethodViewResolver

connexion/apps/flask_app.py
Fixes the interaction of the debug mode with available server options.
When having `debug=True` and specify `server` argument, the application currently has the interaction as below:
- `server='flask'`: this works correctly and the application is updated when users edit a file
- `server='tornado'`: no update when users edit a file
- `server='gevent'`: no update when users edit a file
- for tornado, `tornado.autoreload` is enabled if debug is true
- for gevent, because it doesn't support automatic detection for code changes, the application'll display a log message suggesting users to try other options
=> debug mode interaction for non-flask server

tests/api/test_bootstrap.py
Flask no longer allows you to register routes on an application after it has processed its first request. This broke one of our tests adding routes to an application provided by a fixture. I changed this so a new application object is constructed for the test.
=> Fix tests for flask 2.2

.pre-commit-config.yaml, connexion/__init__.py, connexion/apis/abstract.py, connexion/cli.py, connexion/decorators/validation.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/security.py, connexion/middleware/swagger_ui.py, connexion/resolver.py, connexion/spec.py, tox.ini
=> Activate mypy check in pre-commit

connexion/decorators/uri_parsing.py, tests/decorators/test_uri_parsing.py
=> fix: don't interpret simple parameter as deepObject

connexion/cli.py
In Python 3, `list(dict)` is often a better way to express `dict.keys()`
Related to #1560 -- @RobbeSneyders @nielsbox Your review, please.
=> Remove "type: ignore" by using list(dict), not dict.keys()

connexion/apps/flask_app.py, connexion/jsonifier.py, connexion/middleware/swagger_ui.py, setup.py, tests/api/test_responses.py, tests/test_flask_encoder.py
Partially fixes #1576 by updating the jsonifier and related code to be compatible with Flask 2.3.
Since this new json interface in Flask was only introduced in Flask 2.2, we'll have to pin it as the lower bound version.
I'm doubting if we should backport this to v2. It introduces some breaking changes for users who use custom json encoders, and it would force us to bump the lower bound version of Flask to 2.2 there as well.
If we don't do a backport, we should pin the upper bound Flask version on v2 to 2.2 instead.
=> Update json for Flask 2.3

connexion/__init__.py, connexion/apis/flask_api.py, connexion/jsonifier.py, tests/test_middleware.py
Fixes #1576 
Another deprecation warning for Flask 2.3.
Also suppressed first party `DeprecationWarning`s for which I had to add a `pytest.ini` file. Since we have quite a lot of config files, we might want to move them to a `pyproject.toml` file in the future.
=> Use Flask request_ctx instead of _request_ctx_stack

connexion/apis/__init__.py, connexion/apis/abstract.py, connexion/middleware/swagger_ui.py
This PR removes the `AbstractSwaggerUIAPI` class, which was a temporary base class used to support the swagger UI both in the Flask App & Middleware. Since the swagger UI has been moved completely into the middleware, we don't need it anymore.
=> Remove AbstractSwaggerUIAPI class

connexion/apis/abstract.py, connexion/apps/abstract.py, connexion/decorators/parameter.py, connexion/middleware/security.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/security/security_handler_factory.py, examples/openapi3/helloworld/hello.py, tests/conftest.py, tests/decorators/test_parameter.py, tests/fakeapi/hello/__init__.py
Fixes #1532 .
- I removed the parameter _pass_context_arg_name_ passed internally as asked from the various constructors, and left in the _SecurityHandlerFactory_ a constant called **_context_kw_**, following the same pattern of _required_scopes_kw_. 
I don't know if it is better to put in uppercase both values (_context_kw and required_scopes_kw_), now they are constants in the end. 
I left as the other one to have consistency, but if you prefer I can change them both.
=> Removed internal variable pass_context_arg_name

setup.py, tests/api/test_bootstrap.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Fixes #1529
Flask async routes were already supported due to the async logic used for `aiohttp`. This PR just makes it explicit by:
- Installing Flask with the `async` extra.  
The additional `asgiref` dependency it adds is already a subdependency of connexion though, so in practice this has no effect.
- Adding a test checking if async routes work
=> Explicitly support Flask async routes

connexion/middleware/__init__.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/routing.py, connexion/middleware/security.py, connexion/middleware/swagger_ui.py, connexion/middleware/validation.py, setup.py, tests/test_operation2.py
As mentioned in #1588, we're repeating a lot of boilerplate across the middlewares. This PR extracts this boilerplate into shared base classes. Feel free to propose better naming for them :slightly_smiling_face: 
I had to revert the order of Middleware - Api - Operation to Operation - Api - Middleware due to dependencies in the typing.
=> Extract boilerplate code into Routed base classes

connexion/decorators/validation.py
- Accessing jsonschema.draftN_format_checker is now deprecated. Use Draft4Validator.FORMAT_CHECKER when possible (jsonschema >= 4.5.0)
=> Avoid warning with jsonschema 4.16.0

connexion/decorators/validation.py, connexion/middleware/request_validation.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/validators.py, tests/decorators/test_validation.py, tests/test_operation2.py
This PR moves Swagger 2 form validation to the middleware by translating the Swagger 2 form parameter definition into an OpenAPI 3 RequestBody JsonSchema spec. This allows us to use the `FormDataValidator` introduced in #1595 for Swagger 2 as well instead of the old `ParameterValidator`.
=> Move Swagger 2 form validation to middleware

connexion/datastructures.py, connexion/middleware/request_validation.py, connexion/operations/openapi.py, connexion/validators.py, tests/api/test_schema.py, tests/fakeapi/hello/__init__.py, tests/fixtures/different_schemas/openapi.yaml, tests/fixtures/different_schemas/swagger.yaml
This PR adds support for [media-ranges](https://www.rfc-editor.org/rfc/rfc7231#section-5.3.2).
- In the [specification](https://swagger.io/specification/#request-body-object).
- In the connexion `validator_map`, which allows to define a validator for a range of media types. I updated the default `validator_map` to use the `JsonRequestBodyValidator` for all json media types, which is in line with [Connexion 2 behavior](https://github.com/spec-first/connexion/blob/main/connexion/utils.py#L137).
=> Support media-range via MediaTypeDict

connexion/datastructures.py, connexion/decorators/validation.py, connexion/middleware/request_validation.py, connexion/middleware/response_validation.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/validators.py, setup.py, tests/api/test_schema.py, tests/decorators/test_validation.py, tests/fakeapi/hello/__init__.py, tests/fixtures/different_schemas/openapi.yaml, tests/fixtures/different_schemas/swagger.yaml, tests/test_operation2.py
This PR moves form data validation to the middleware, which is quite complex due to differences between Swagger 2 and OpenAPI 3 in how form data is represented.
For OpenAPI 3, this is quite simple. The form data is represented as an object in the request body, which means we can just use a request body validator.
For Swagger 2, this is more complicated. The form data is represented as parameters instead. I see two options here:
- We validate the form data as parameters, which is what Connexion is currently doing. The advantage is that you can easily use the current parameter validation with the spec. The downside is that it's different from OpenAPI 3 and you need to consume the stream in the parameter validation.
- We transform the FormData parameters in the Swagger2Operation to a body …
=> Add form data validator for validation middleware

connexion/apps/flask_app.py
Fixes the problem of non-exceptional "exceptions" being recorded by telemetry systems as a serious error. This expands on the changes made in #1326. The intention of that other change seems to be making telemetry systems like Sentry record serious errors. Diving into the Sentry implementation even shows that the signalled exception is recorded at "level" = "error". 
The root of the problem is that exceptions are being used for control flow, which is not ideal - convenient for app writers but not always for library maintainers. The connexion BadRequestProblem and NotFoundProblem, for example, should not be recorded as an error in a telemetry system. In my case [elastic-apm-python](https://github.com/elastic/apm-agent-python) is receiving these signals and recording 4xx events as serious …
=> Flask apps only signal an exception on real server errors

connexion/options.py, setup.py, tests/api/test_responses.py
Fixes #1412
Fixes #1516 
Since [swagger-ui-bundle](https://github.com/dtkav/swagger_ui_bundle) is no longer maintained, I forked it under the spec-first organization as [py-swagger-ui](https://github.com/spec-first/py-swagger-ui). This PR updates connexion to use it instead.
=> Switch to own maintained version of swagger-ui

connexion/apps/asynchronous.py, connexion/decorators/main.py, connexion/middleware/abstract.py, connexion/validators/__init__.py, connexion/validators/json.py, examples/enforcedefaults/app.py, examples/enforcedefaults/spec/openapi.yaml, examples/enforcedefaults/spec/swagger.yaml, examples/sqlalchemy/spec/openapi.yaml
This PR is a proposal to enforce defaults in json bodies.
I'm not sure which way to go here
- I think connexion should offer the functionality to fill in the defaults, as this helps enforce the contract. If a value is not provided, the application gets the default. We should probably offer this using a simple `default` flag instead of the custom validator now needed.
- I don't like that validation adapts the body. Validation is a read-only operation and it would be nice to keep it that way.
- Splitting enforcing defaults from validation would be less efficient since we'd need to traverse the body multiple times.
If we do want to go this way, we should probably implement a similar fix for form data, as we also use json validators there.
=> Enable enforcing defaults

connexion/operations/swagger2.py
Fixes a small todo I left in the code before to cache the body definition on the operation.
=> Cache operation body definition

connexion/uri_parsing.py, connexion/validators/form_data.py, connexion/validators/parameter.py, tests/api/test_parameters.py, tests/api/test_unordered_definition.py, tests/decorators/test_validation.py, tests/test_validation.py
This PR moves all type coercing into the URI parsers and makes sure it's only done once for each code path.
=> Coerce types only in uri parser

tests/api/conftest.py, tests/api/test_bootstrap.py, tests/api/test_secure_api.py, tests/conftest.py, tests/decorators/test_security.py, tests/test_api.py, tests/test_flask_encoder.py, tests/test_json_validation.py, tests/test_middleware.py, tests/test_operation2.py, tests/test_resolver_methodview.py
This PR refactors our tests to prepare the activation of our tests for our AsyncApp.
The separate commits are atomic, which can be useful for reviewing.
=> Refactor tests

connexion/decorators/parameter.py, connexion/decorators/response.py, connexion/frameworks/flask.py, connexion/frameworks/starlette.py, connexion/lifecycle.py, connexion/middleware/security.py, tests/decorators/test_parameter.py
This PR defines a request interface and aligns the `ASGIRequest` with the `WSGIRequest` class. This brings down the test errors from 62 to 25.
=> Define request interface and align WSGI and ASGI

connexion/__init__.py, connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/context.py, connexion/decorators/parameter.py, connexion/decorators/response.py, connexion/frameworks/flask.py, connexion/frameworks/starlette.py, connexion/lifecycle.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/security.py, tests/api/test_errors.py, tests/api/test_responses.py, tests/decorators/test_parameter.py, tests/fakeapi/example_method_class.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml, tests/test_resolver_methodview.py
This PR adds all the needed error handling for the AsyncApp.
Only 5 errors remaining.
=> Add error handlers for AsyncApp

connexion/frameworks/flask.py, examples/helloworld/spec/openapi.yaml, tests/api/test_parameters.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Fixes #1635
See https://github.com/pallets/werkzeug/issues/2518. 
Apparently, this is only an issue when you have more than 1 path parameter, so added a test for that.
=> Update NumberConverter regex to match new Werkzeug behavior (v3)

connexion/decorators/parameter.py, tests/api/test_parameters.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Fixes #992
This PR re-adds tests that were removed when dropping aiohttp, as raised in https://github.com/spec-first/connexion/issues/1395#issuecomment-1175591898.
=> Re-add tests for multiple and mixed file uploads

connexion/json_schema.py, connexion/spec.py, tests/conftest.py, tests/fixtures/relative_refs/components.yaml, tests/fixtures/relative_refs/definitions.yaml, tests/fixtures/relative_refs/openapi.yaml, tests/fixtures/relative_refs/swagger.yaml, tests/test_api.py
Fixes #254 
Fixes #967 
This PR fixes the very long-standing issue of being able to handle relative references, which allows users to split their specification into multiple files.
=> Add support for relative refs in spec

connexion/__init__.py, connexion/apps/flask.py, connexion/exceptions.py, connexion/handlers.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/response_validation.py, connexion/mock.py, connexion/problem.py, connexion/resolver.py, connexion/security.py, connexion/validators/form_data.py, connexion/validators/json.py, connexion/validators/parameter.py, tests/api/test_errors.py, tests/api/test_headers.py, tests/api/test_secure_api.py, tests/decorators/test_security.py, tests/fakeapi/hello/__init__.py, tests/test_api.py, tests/test_cli.py, tests/test_json_validation.py
Fixes #1414 
Fixes #590
Fixes #945 
Fixes #958 
Fixes #964 
And generally cleans up the exception module with a consistent interface across errors and a correct hierarchy.
=> Clean up errors and fix hierarchy

connexion/middleware/exceptions.py, connexion/middleware/request_validation.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/validators/form_data.py, connexion/validators/json.py, tests/api/test_responses.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml, tests/test_operation2.py
=> Enforce required RequestBody

connexion/json_schema.py, connexion/middleware/exceptions.py, connexion/middleware/request_validation.py, connexion/middleware/response_validation.py, connexion/operations/swagger2.py, connexion/validators/__init__.py, connexion/validators/abstract.py, connexion/validators/form_data.py, connexion/validators/json.py, tests/api/test_parameters.py, tests/test_json_validation.py, tests/test_operation2.py
As promised, an `AbstractRequestBodyValidator` class. This has 2 advantages:
- Groups all common code
- Provides a base for custom validators
Looking at the remaining logic in the subclasses, I'm quite happy with the current abstraction. A lot of the complexity comes from substituting the default body when no body is received.
I'll leave some additional comments in-line.
=> Create abstract validator classes

connexion/decorators/response.py, connexion/middleware/request_validation.py, connexion/middleware/response_validation.py, connexion/operations/openapi.py, tests/api/test_responses.py, tests/fixtures/simple/openapi.yaml
Addresses a todo left in the code.
We only validate the mimetype if the spec defines which mime-types it produces, and only for non-error responses.
=> Enable response mimetype validation for non-error responses

connexion/json_schema.py, tests/fixtures/json_validation/openapi.yaml, tests/test_json_validation.py
Fixes #942 
No longer return 400 if a read-only property is provided, as discussed in the issue. We still raise an error if write-only properties are included in the response and response validation is enabled.
I also changed how read-/write-only works in combination with `required`. Previously, `required` would not be overwritten by read-/write-only. Now we just follow the spec to the letter:
- required and read-only: must be included but must be ignored by the server
- required and write-only: impossible to achieve, but I also don't see how this combination could make sense
- read-only: may be included but must be ignored by server
- write-only: must not be included by server
=> Don't return 400 when read-only property is provided

connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/middleware/abstract.py, connexion/middleware/main.py, connexion/middleware/swagger_ui.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, tests/test_flask_encoder.py, tests/test_mock.py, tests/test_mock3.py, tests/test_operation2.py, tests/test_resolver.py, tests/test_resolver3.py, tests/test_resolver_methodview.py
This PR adds a `jsonifier` argument to the app and api to align it with other customization options. We also no longer pass it via the operation object, which brings us closer to operations as data class only.
=> Add jsonifier as argument to app / api

docs/quickstart.rst
- Updated the docs such that it comes with an example for passing server arguments and serving static files
=> Update quickstart.rst to include example of passing server arguments

connexion/__init__.py, connexion/decorators/main.py, connexion/decorators/parameter.py, connexion/utils.py, tests/decorators/test_parameter.py
This PR delays import errors for the optional Flask dependency, so you can use the AsyncApp without Flask installed.
This issue is hidden in our tests since we install all extras. To prevent this, we need to address https://github.com/spec-first/connexion/issues/1389.
=> Delay import error for optional flask depencendy

connexion/apps/asynchronous.py, connexion/apps/flask.py
Fixes #1666 
The `FlaskOperation` and `AsyncOperation` classes act as decorators for their wrapped view functions, so their metadata should reflect this, similar to what `functools.wraps` does.
=> Update Operations to act as wrapper of wrapped view function

pyproject.toml
We use `asgiref` as a direct dependency
https://github.com/spec-first/connexion/blob/ab94e2aaa67d30ab2bb97e4d8d27746a5ed43d20/connexion/decorators/main.py#L7
So should add it explicitly as well.
This issue is hidden in our tests since we install all extras. To prevent this, we need to address https://github.com/spec-first/connexion/issues/1389.
=> Add explicit asgiref dependency

connexion/middleware/swagger_ui.py, tests/test_middleware.py
Fixes #1672
Lifespan events were being intercepted by the swagger UI middleware. We should let them pass through.
=> Pass through lifespan events

connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/lifespan.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/swagger_ui.py, tests/test_lifespan.py, tests/test_middleware.py
This PR adds a new middleware to handle lifespan events.
I added this as a separate middleware so it is encapsulated and aligned for both the `FlaskApp` and `AsyncApp`. It leverages a Starlette `Router` to register and call the lifespan handler.
=> Add lifespan middleware

docs/security.rst
Contributes to #1531 
The links in security doc were pointing at an old repo and folders.
These links could be changed down the road to use relative paths since they point to the repo internally.
=> Fix examples links in security doc page

connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/middleware/main.py, connexion/middleware/request_validation.py, connexion/middleware/security.py, connexion/security.py, connexion/validators/parameter.py, tests/api/test_secure_api.py, tests/decorators/test_security.py, tests/test_operation2.py
=> Make security pluggable

tests/api/conftest.py, tests/api/test_secure_api.py, tests/fixtures/secure_endpoint/openapi.yaml, tests/fixtures/secure_endpoint/swagger.yaml, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
Continues on the work of #1077 by moving the test fixtures into the `secure_endpoint` fixture and adding a test for it in `test_secure_api.py`.
The test will check whether an api key in the query will not lead to an error when `strict_validation` is enabled.
=> Add tests for strict validation in combination with api key in query

connexion/apps/abstract.py, connexion/middleware/__init__.py, connexion/middleware/main.py, tests/api/test_bootstrap.py, tests/conftest.py, tests/test_cli.py
This PR adds an `add_middleware` method to the apps and `ConnexionMiddleware` to easily add middleware to the stack. Before, the only way to do this was to pass in a complete middleware stack.
The default position to add the new middleware is right before the `ContextMiddleware`, which is the final middleware in the stack. Another position can be selected by passing in a `MiddlewarePosition` enum, which defines some positions which make sense.
Since we can no longer assume that the whole middleware stack is defined when initializing the `ConnexionMiddleware`, we need to delay building the middleware stack until the `ConnexionMiddleware` is actually called. This also means we need to delay registering the APIs and error handlers. This is now all done in the `_build_middleware_stack` …
=> Add `add_middleware` interface

tests/api/test_secure_api.py, tests/fakeapi/hello/__init__.py, tests/fixtures/secure_api/openapi.yaml, tests/fixtures/secure_api/swagger.yaml
Follow-up of #1671 
Let me know if there is an easier way doing the test instead of the current "custom" basic auth.
=> Add test for security_map argument

connexion/decorators/parameter.py, connexion/middleware/abstract.py, connexion/middleware/exceptions.py, connexion/middleware/lifespan.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/swagger_ui.py, connexion/utils.py, tests/test_middleware.py
Fixes #1682 
This PR inspects the parameters of a Middleware class before passing in the `lifespan` keyword argument. I was doubting to check the class instead (`isinstance(LifespanMiddleware)`), but that's less flexible if users want to write custom middleware to handle the lifespan.
=> Inspect middleware parameters before passing in lifespan

connexion/security.py
Follow-up on #1671 
Since the request context is available globally, we can remove this complexity from the security handlers ("There should be one-- and preferably only one --obvious way to do it.")
In addition it seems like there weren't any tests for the context in security handler functions, and I don't think there's a lot of value in a test for checking the context in security functions specifically.
=> Remove context keyword from security handlers

connexion/middleware/main.py, tests/api/test_bootstrap.py
Registering error handlers on the async app leads to an error on 3.0.0a5 because the error handlers are not unpacked correctly when being registered internally.
=> Unpack error handler when registering on middleware

connexion/middleware/main.py, tests/api/test_errors.py, tests/test_middleware.py
Fixes #1697
Because of a wrong comparison against the position `Enum`, middleware was not actually being added to the stack via `add_middleware`. This PR fixes this, adds a warning when the middleware position cannot be found, and adds a test.
=> Fix add_middleware enum comparison

docs/index.rst
Contributes towards #1531 
Improves the high level explanation of Connexion and fixes broken links on the index page.
=> Improve and fix docs index page

connexion/middleware/exceptions.py
Still up for discussion: right now, when an internal server error occurs, the logged error is not really useful for the user.
For example, a `KeyError` will only print the missing key instead of the full stacktrace and error.
Adding it to the common error handler as that one is meant to catch all remaining errors, `HTTPException`s are handled by another error handler.
Another option would be to do like `Flask` and `Starlette` by adding a `debug` option, but that seems a lot of work while this current solution doesn't really have big downsides (?)
=> Add traceback info to common error handler

connexion/middleware/main.py, docs/index.rst, docs/middleware.rst
Contributes towards https://github.com/spec-first/connexion/issues/1531
This PR adds a documentation page on middleware.
=> Add middleware documentation

connexion/validators/abstract.py
Fixes the failing pipeline.
I don't understand the underlying issue completely, but It's related to [this code](https://github.com/encode/starlette/compare/0.27.0...0.28.0#diff-87bccafe494bc79680d9d8f57ea797733354b076aa411c0e2bd63f5b4039f71fR51-R54) added in starlette 0.28. This makes the scope unpicklable in some cases, leading to an error when trying to deepcopy it.
I replaced the deepcopy of the whole scope with just a deepcopy of the headers, since this is the only part we're chaning.
=> Deepcopy only headers in validator

docs/context.rst, docs/index.rst
Contributes towards #1531 
Fixes #937
=> Add context documentation

.github/workflows/pipeline.yml, connexion/apps/flask.py, connexion/cli.py, pyproject.toml, tests/decorators/test_parameter.py, tests/test_api.py, tox.ini
Python 3.7 is end of life. We should support the newer versions instead.
I also changed tox to only run against the minimum dependency versions on the lowest Python version, since this should lead to the lowest versions over all Python versions, and hopefully helps speed up our pipelines :)
=> Drop Python 3.7 in favor of 3.11 and 3.12

connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/context.py, connexion/decorators/parameter.py, connexion/frameworks/starlette.py, connexion/lifecycle.py, connexion/middleware/exceptions.py, connexion/middleware/main.py, connexion/middleware/security.py, connexion/security.py, connexion/types.py, docs/context.rst, docs/request.rst, docs/routing.rst, docs/v3.rst, tests/decorators/test_security.py
I was writing the documentation on exception handling, and I noticed that it was very hard to explain our current behavior. 
Error handlers can be registered either on the internal Flask app (not the Starlette one) or on the Connexion app, which leads to some undefined (actually just really hard to explain) behavior. Eg.
- Registering error handlers on a status code would capture `starlette.HTTPException` errors on the Connexion app, and `werkzeug.HTTPException` errors on the Flask App, which means that registering an error handler on a status code doesn't catch all the errors with that status code.
- Flask does some default error handling which leads to some exceptions never reaching the error handlers registered on the Connexion app.
So I made the following changes:
- Replaced the …
=> Centralize error handling in ExceptionMiddleware

connexion/middleware/exceptions.py, connexion/middleware/main.py, docs/index.rst, docs/lifespan.rst
Contributes towards https://github.com/spec-first/connexion/issues/1531
=> Add lifespan documentation

connexion/apps/abstract.py, docs/testing.rst
Contributes towards https://github.com/spec-first/connexion/issues/1531
=> Add testing documentation

connexion/security.py, docs/conf.py, docs/routing.rst, docs/security.rst, examples/oauth2/mock_tokeninfo.py, examples/oauth2_local_tokeninfo/app.py, pyproject.toml
=> Update security docs

LICENSE, LICENSE.txt, NOTICE, pyproject.toml
This PR adds a copyright notice for the new authors / maintainers of connexion. It also reformats the license / notice files as prescribed by the license.
=> Add new authors' copyright notice

connexion/validators/form_data.py, connexion/validators/json.py, tests/api/test_errors.py
Fixes #1152.
Currently, when a request body is empty, the JSON request validator would parse it into None, which is later passed down to the JSON Schema validator. However, jsonschema's validation error message for this case (when nullable is false) "None is not of type 'object'" is not particularly friendly to either the API user, nor the website developer.
This change adds a specific check before the None value is passed to jsonschema to emit a better error message directly.
I also added some drive-by improvements on function argument typing since _validate in validators don't seem to expect receiving None, but _parse (the result of which is passed to _validate) is totally allowed to return None (or anything really). This does not seem to reflect the logic well.
I’m not exactly sure if …
=> Improve JSON req error on disallowed empty body

connexion/options.py, pyproject.toml
Tested with `swagger-ui-bundle==1.1.0` from Test PyPI.
Opening this as a draft PR, since I didn't publish `swagger-ui-bundle` to the main PyPI yet, which I would like to do shortly before we release Connexion 3. 
Before Connexion 2.8, the `swagger_ui_bundle` version didn't have an upper bound. So if anyone runs into any issues because of this update, I'd rather have them come look for answers when Connexion 3 is out.
=> Switch back from py-swagger-ui to swagger-ui-bundle

docs/quickstart.rst, docs/v3.rst
Discussions in #1757 indicate that we should document this more clearly.
=> Improve ASGI server documentation

connexion/apps/flask.py, connexion/http_facts.py, connexion/lifecycle.py, connexion/middleware/exceptions.py, docs/exceptions.rst, docs/v3.rst, tests/api/test_bootstrap.py
Fixes #1787 
In the `FlaskApp`, the error handlers were still registered on the underlying Flask app instead of on the `ExceptionMiddleware`, which led to them not following the documented behavior.
The documentation was also incorrect about ignoring error handlers registered on the flask application. We are only ignoring the default error handlers registered by Flask itself.
This is a breaking change, however, since this functionality was not following the documented behavior, and 3.0.0 was only recently released, I propose to release this as a patch version.
=> Fix FlaskApp exception handlers

docs/middleware.rst
I'm starting to use the project with the newly release 3 version.
https://github.com/spec-first/connexion/blob/70084bcc4c21713cbf861841ebda977263d3ab8c/docs/middleware.rst?plain=1#L115-L120
It seems this example is not correct. 
1. missing import for SecurityMiddleware
2. `ConnexionMiddleware.default_middlewares` is a list of classes, not class instances: the filtering never happen.
=> Fix middleware doc example

docs/conf.py
Fixes #1797 
[Relevant docs](https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html#github).
=> Fix 'Edit on GitHub' link on docs

connexion/decorators/parameter.py, connexion/validators/form_data.py, docs/request.rst, pyproject.toml, tests/api/test_parameters.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml, tests/fixtures/simple/swagger.yaml
=> Fix multiple file upload

docs/cookbook.rst
Updates the import statements on https://connexion.readthedocs.io/en/stable/cookbook.html
A few of the import statements were missing, or didn't match the example code because they imported at the wrong depth.
This should make the code in the cookbook copy-pasteable.
=> Update the import statements for the cookbook snippets

connexion/apps/flask.py, connexion/types.py, docs/middleware.rst, tests/test_middleware.py
As discussed in #1807.
Allowing the injection of WSGI middleware can enable easier migration from Connexion 2 to Connexion 3. The use cases are limited though, as this will only work for middleware that can work at the end of the middleware stack.
=> Add interface to add WSGI middleware

.pre-commit-config.yaml, connexion/middleware/abstract.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/security.py, connexion/middleware/swagger_ui.py, connexion/operations/abstract.py, connexion/spec.py, examples/helloworld/hello.py, tests/test_api.py
Fixes #1801 
I had to make quite a few additional changes to satisfy mypy.
=> Only instantiate specification once

connexion/middleware/main.py, connexion/middleware/server_error.py, docs/cookbook.rst, docs/middleware.rst, tests/api/conftest.py, tests/api/test_cors.py
Fixes #1820.
Correct error handling in response to CORS.
- Add a MiddlewarePosition before Exception handling so CORS is always returned
- Add ServerError Middleware to handle unhandled errors between the ServerError- and ExceptionMiddleware
- Update corresponding docs
=> Fix CORS headers not set on exceptions

pyproject.toml
Temporary fix for https://github.com/spec-first/connexion/issues/1826
We should release this asap.
=> Set starlette upperbound version to <0.33

connexion/spec.py, tests/api/conftest.py, tests/api/test_swagger_ui.py
Fixes #1829.
- Use _raw_spec when cloning
=> Specification use raw spec on clone

docs/quickstart.rst
Small fix to the example code in the documentation for using the `a2wsgi` workaround. The `app` variable is not defined prior to `app = ConnexionMiddleware(app)`
=> Fix quickstart WSGI example typo

docs/cookbook.rst, examples/reverseproxy/app.py, pyproject.toml, tests/api/conftest.py
Starlette introduced some new changes to how the `root_path` is handled, which broke our `ReverseProxied` example and test.
This PR fixes both and adds documentation on how to run behind a proxy.
=> Fix ReverseProxied middleware and add docs

docs/quickstart.rst, docs/v3.rst
(One was enountered manually, the other found via Sphinx's builtin linkcheck builder, which also confirms there aren't really any others.)
I often suggest using Sphinx's [`default_role`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-default_role) setting to make writing docs quite a bit less noisy in a fairly uncontroversial way. A toxenv / docs setup in CI also seems like a decent idea. As is, there is a small part of the docs which isn't being rendered because it contains errors (in the output below it's the one `CRITICAL`), and there are some other interlinks which are broken. Essentially, IMHO, running Sphinx without `-n -T -W` is a recipe for brokenness unfortunately. This is what one sees when doing so, even after this PR:
<details>
``` …
```
=> Fix two broken links in the docs.

connexion/uri_parsing.py, tests/fakeapi/hello/__init__.py, tests/fixtures/json_validation/openapi.yaml, tests/test_json_validation.py
Fixes #1869 .
- Prioritise parsing JSON over splitting array
=> Fix for JSON array parsing in multipart/form-data (#1869)

connexion/validators/form_data.py
Fixes #1825 
Files can be encoded as bytes or base64 ([openapi docs](https://swagger.io/docs/specification/describing-request-body/file-upload/)), we were only handling bytes before.
=> Fix file upload for base64 encoded files

connexion/apps/abstract.py, connexion/cli.py, connexion/middleware/main.py, connexion/spec.py, docs/cli.rst, tests/test_api.py
- Allow a specification to be specified as a URL that is downloaded when the App runs. In combination with the existing mock features, this makes it a single command to run a mock server for any published API.
=> Allow the specification to be specified as a URL.

connexion/security.py, docs/security.rst, tests/decorators/test_security.py
Fixes #1881
Fixes #1880
Fixes #1876
Alternative to #1750
This PR makes the current request available to the security handlers by injecting it as a keyword. I think this is a proper alternative to #1750, since this is the only place in the default middleware stack where I expect this to be needed.
=> Inject current request in security handlers

docs/lifespan.rst
Thanks a lot for this amazing tool.
When adding a `lifespan_handler` to my server, it only works if the handler is asynchronously. That is consistent with the [tests](https://github.com/spec-first/connexion/blob/994f53fb045f1668ab84c472f7dc06d093470cf1/tests/test_lifespan.py#L13) but not the documentation. So this PR aims to correct the documentation
=> Fix lifespan example

docs/quickstart.rst
Using openapi spec from quickstart results in
```
connexion.exceptions.InvalidSpecification: {'content': {'text/plain': {'schema': {'type': 'string'}}}} is not valid under any of the given schemas
Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^\\/']['patternProperties']['^(get|put|post|delete|options|head|patch|trace)$']['properties']['responses']['patternProperties']['^[1-5](?:\\d{2}|XX)$']:
{'oneOf': [{'$ref': '#/definitions/Response'},
{'$ref': '#/definitions/Reference'}]}
On instance['paths']['/greeting/{name}']['get']['responses']['200']:
{'content': {'text/plain': {'schema': {'type': 'string'}}}}  
```
because `description` is missing in the spec and it is a required property for `#/definitions/Response`. …
=> Fix openapi spec in quickstart doc

connexion/middleware/exceptions.py, connexion/validators/json.py
Fixes #1925.
- Log handled errors to `warning` instead of `error`.
- Log validation errors to `info` because the intent of the log lines in informational. The error is handled by raising a new error.
=> Log handled errors to warning

connexion/middleware/exceptions.py, connexion/validators/json.py
@RobbeSneyders, @Ruwann sorry for this, it seems like I've sneaked in a duplicate log statement in PR #1926 🙇‍♂️
=> Remove duplicate log statement that was forgotten in the context of PR #1926.

connexion/validators/parameter.py, tests/decorators/test_uri_parsing.py, tests/test_validation.py
During the refactoring for Connexion 3, we deduplicated all `coerce_type` calls during the refactoring and moved them into the `uri_parser` so it is done in a single place. When looking into #1931 however, I noticed we are still using the `uri_parser` from more places than we should.
This PR centralizes the parsing further into the `ConnexionRequest` class. During validation, we now instantiate a `ConnexionRequest` instead of a Starlette `Request`, and leverage it instead of calling the `uri_parser` directly.
I split the parsing and validation in the tests so they can be tested in isolation.
=> Split parsing from validation completely

connexion/decorators/response.py, connexion/middleware/response_validation.py, tests/api/test_responses.py, tests/fakeapi/hello/__init__.py, tests/fixtures/simple/openapi.yaml
Fixes #1917  .
- Look at enum value for return status code if given
-
-
=> Can return HTTPStatus member when default response is declared

docs/security.rst
After going back and forth because I kept having a "module not found" error, I finally tried to use the complete path. 
I realized afterward that the doc specified you had to use "explicit" routing but I set up the routing so long ago that it didn't click. I was focused on the "same syntax that is used to connect an operationId". 
This may not be the best way to clarify it (maybe a Troubleshooting section ?) but I just thought I would make a suggestion.
Thanks for your work !
=> auth module documentation suggestion

connexion/validators/form_data.py, connexion/validators/json.py, docs/validation.rst
=> [#1786] Address jsonschema format_checker deprecation

tests/decorators/test_validation.py
Not sure why this behavior changed on some Python versions.
=> Fix failing test

.pre-commit-config.yaml, connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/exceptions.py, connexion/frameworks/abstract.py, connexion/frameworks/flask.py, connexion/frameworks/starlette.py, connexion/middleware/abstract.py, connexion/middleware/main.py, connexion/middleware/routing.py, connexion/middleware/security.py, connexion/operations/abstract.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, connexion/testing.py
Improve type hints for arguments that are nullables and fix _flake8_ pre-commit hook.
- Update _pre-commit_ configuration with the latest version of _flake8_ to prevent errors
- Improve type hints for parameters that are nullables
=> Improve type hints nullable parameters

connexion/security.py, tests/decorators/test_security.py, tests/test_operation2.py
Fixes # N/A
The current documentation mentions that API-key
security supports scopes: "
The function should accept the following arguments:
- apikey
- required_scopes (optional) "
However, the scopes were not passed to the checker.
- Add missing parameter routing to ApiKeySecurityHandler
- Add a unit test for API-key scopes
=> Add API-key scope checking

connexion/middleware/request_validation.py, connexion/validators/abstract.py, tests/fixtures/json_validation/openapi.yaml, tests/fixtures/json_validation/swagger.yaml, tests/test_json_validation.py
The actual arg (scope), needs to be updated when the content-length changes.
Fixes #1954 
-
-
-
=> fix: update scope when content-length changes

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Connexion Guru](https://gurubase.io/g/connexion) to Gurubase. Connexion Guru uses the data from this repo and data from the [docs](https://connexion.readthedocs.io/en/latest/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Connexion Guru", which highlights that Connexion now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …
=> Introducing Connexion Guru on Gurubase.io

connexion/apps/abstract.py, connexion/apps/asynchronous.py, connexion/apps/flask.py, connexion/middleware/main.py
Previously documented as options.ConnexionOptions, which does not exist
=> Correct pydoc to show swagger_ui_options param type SwaggerUIOptions

connexion/middleware/swagger_ui.py, connexion/spec.py
Fixes #1909 
This PR uses the already resolved spec when swagger UI requests it.
=> Fix swagger UI for split specs

connexion/apps/flask.py
Also update the grammar for `auth_all_paths`.
The duplicated parameter was added accidentally in 0c0c517cf6d698bd7683e0a516d6aad9564a2f5e.
=> remove duplicate parameter `swagger_ui_options` in docstring for `FlaskApp`

docs/v3.rst
=> Fix name of `hello` module in v3 getting-started doc

connexion/middleware/request_validation.py, connexion/middleware/response_validation.py
In `request_validation.py` and `response_validation.py` there is a call to `logging.info()` which means the log message goes through the root logger instead of the `connexion.middleware.validation` logger.
=> use connexion logger instead of root logger

examples/splitspecs/README.rst, examples/splitspecs/app.py, examples/splitspecs/spec/components.yaml, examples/splitspecs/spec/definitions.yaml, examples/splitspecs/spec/openapi.yaml, examples/splitspecs/spec/swagger.yaml
Store the API in one file, the schema definitions in another file
=> Add example of split API specifications with relative references

examples/apikey/README.rst, examples/basicauth/README.rst, examples/enforcedefaults/README.rst, examples/frameworks/README.rst, examples/helloworld/README.rst, examples/helloworld_async/README.rst, examples/jwt/README.rst, examples/jwt/requirements.txt, examples/jwt/spec/openapi.yaml, examples/methodresolver/README.rst, examples/oauth2/README.rst, examples/oauth2_local_tokeninfo/README.rst, examples/restyresolver/README.rst, examples/reverseproxy/README.rst, examples/sqlalchemy/README.rst, examples/sqlalchemy/requirements.txt
Add server url /openapi to JWT example
Add TODO to SQLAlchemy example, does not work with current versions
Correct name of module in v3 instructions
Fixes #1987
=> Document how to install prerequisites in examples READMEs

connexion/mock.py, connexion/operations/openapi.py, connexion/operations/swagger2.py, tests/test_mock.py, tests/test_mock3.py
There's never a need to return a response for HTTP 204 - and these code are unlikely to have any "example" response documented  in the spec.
Avoids a uvicorn RuntimeError `"Response content longer than Content-Length"` when mocking a (3.0) spec containing:
```
...
responses:
'204':
description: No Content
'401':
description: Unauthorized
content:
application/json:
schema:
$ref: '#/components/schemas/ProblemDetails'
...
```
* We could also move this `if/else` check into the operation's `example_response` method. Thoughts?
=> Return NoContent when mocking HTTP 204 operations

examples/sqlalchemy/README.rst, examples/sqlalchemy/app.py, examples/sqlalchemy/orm.py
Pass argument that disables SQLite thread check when creating the engine
Revise request-processing functions to work within a database session context
Drop TODO from the example README
=> Update example for latest version of SQLAlchemy

examples/sqlalchemy/app.py
When trying to work with this example I received the error:
```bash
AttributeError: module 'datetime' has no attribute 'UTC'
```
Doing some research, it seems the new pattern is to pull UTC from timezone. Making the suggested edit as a PR
Fixes # .
-
-
-
=> Update sqlalchemy example to work with Python 3.8, 3.9 and 3.10

connexion/middleware/main.py
- Update docstring of `connexion.ConnexionMiddleware.add_api` to match return value to actual return.
=> Update docstring of `connexion.ConnexionMiddleware.add_api`

pyproject.toml
Fixes the mypy error that is causing all pipelines to fail. Underlying reason seems to be that the `jsonschema` library was updated and factored out some code into a separate package. So updated it to also reference that file in our mypy overrides.
Might be fixed for newer versions by this recent commit https://github.com/python-jsonschema/referencing/commit/f830e4c8d6a3b9b792d091ee8c6ac2eafbcf0de0
=> Specify skip for separate referencing package
